import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { jsonNoCache } from "@/lib/api-utils";
import { readJsonStore, writeJsonStore } from "@/lib/json-store";

export const dynamic = "force-dynamic";
export const revalidate = 0;

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || "https://placeholder.supabase.co";
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "placeholder-key";

const supabase = createClient(supabaseUrl, supabaseKey);

const MASTER_TOUR_LOGS = [
  {
    "tourcode": "SOO220528",
    "start_date": "29-May-2022",
    "end_date": "09-Jun-2022",
    "days": 12,
    "qty": 1,
    "location": "Sri Phala Resort And Villa",
    "tl": "Usman",
    "status": "Finish",
    "modems": "NET11",
    "invoice_status": "Paid",
    "remark": "Lombok"
  },
  {
    "tourcode": "SOO220604S",
    "start_date": "05-Jun-2022",
    "end_date": "17-Jun-2022",
    "days": 13,
    "qty": 9,
    "location": "Swastika Bungalow",
    "tl": "Komang Karung",
    "status": "Finish",
    "modems": "NET01, NET02, NET03, NET04, NET05, NET06, NET07, NET08, NET09",
    "invoice_status": "Paid",
    "remark": "Pax 24"
  },
  {
    "tourcode": "KIB220702",
    "start_date": "03-Jul-2022",
    "end_date": "15-Jul-2022",
    "days": 13,
    "qty": 1,
    "location": "Bhuwana Ubud",
    "tl": "Sofyan Manik",
    "status": "Finish",
    "modems": "MC1",
    "invoice_status": "Paid",
    "remark": "12345678990"
  },
  {
    "tourcode": "BAT220702",
    "start_date": "03-Jul-2022",
    "end_date": "14-Jul-2022",
    "days": 12,
    "qty": 3,
    "location": "Champlung Sari Ubud",
    "tl": "Gede Suadnyana",
    "status": "Finish",
    "modems": "NET11",
    "invoice_status": "Paid",
    "remark": "1 modem extend smpe tgl 19, extra charge 300K"
  },
  {
    "tourcode": "AIS220708R",
    "start_date": "09-Jul-2022",
    "end_date": "28-Jul-2022",
    "days": 20,
    "qty": 4,
    "location": "Swastika Bungalow",
    "tl": "Komang Karung",
    "status": "Finish",
    "modems": "NET04, NET05, NET06, NET07",
    "invoice_status": "Paid",
    "remark": "Flores, net 04 isi lagi 60rb tgll 20 jul"
  },
  {
    "tourcode": "FIO220709P",
    "start_date": "10-Jul-2022",
    "end_date": "21-Jul-2022",
    "days": 12,
    "qty": 1,
    "location": "Ramayana Candidasa",
    "tl": "Andi Kurniawan",
    "status": "Finish",
    "modems": "NET22",
    "invoice_status": "Paid",
    "remark": "kirim 12 Jul.22, J&T"
  },
  {
    "tourcode": "FIB220709P",
    "start_date": "10-Jul-2022",
    "end_date": "21-Jul-2022",
    "days": 12,
    "qty": 4,
    "location": "Bhuwana Ubud",
    "tl": "Panji Sidarta",
    "status": "Finish",
    "modems": "NET12, NET23",
    "invoice_status": "Paid",
    "remark": "Book by Bu Peri Net12 rusak, diganti dengan NET23"
  },
  {
    "tourcode": "KID220714B",
    "start_date": "15-Jul-2022",
    "end_date": "03-Aug-2022",
    "days": 20,
    "qty": 2,
    "location": "Sukajadi Bandung",
    "tl": "Sugiarto",
    "status": "Finish",
    "modems": "NET1, NET14",
    "invoice_status": "Paid",
    "remark": "Kirim 12 Jul.22"
  },
  {
    "tourcode": "BAJ220714R",
    "start_date": "15-Jul-2022",
    "end_date": "03-Aug-2022",
    "days": 20,
    "qty": 5,
    "location": "Erian Hotel Jakarta",
    "tl": "Bram Idrus",
    "status": "Finish",
    "modems": "NET12, NET15, NET16, NET17, NET18",
    "invoice_status": "Paid",
    "remark": "Book by Bu Peri, kirim tanggal 11 Jul.22"
  },
  {
    "tourcode": "SSN220715",
    "start_date": "16-Jul-2022",
    "end_date": "04-Aug-2022",
    "days": 20,
    "qty": 1,
    "location": "Champlung Sari Ubud",
    "tl": "Pak Yance",
    "status": "Finish",
    "modems": "NET08",
    "invoice_status": "Paid",
    "remark": "Bali Tour"
  },
  {
    "tourcode": "FIO220716B",
    "start_date": "17-Jul-2022",
    "end_date": "29-Jul-2022",
    "days": 12,
    "qty": 1,
    "location": "Champlung Sari Ubud",
    "tl": "Ibu Widi",
    "status": "Finish",
    "modems": "NET09",
    "invoice_status": "Paid",
    "remark": "Book by Bu Peri"
  },
  {
    "tourcode": "SOO220716S",
    "start_date": "17-Jul-2022",
    "end_date": "28-Jul-2022",
    "days": 12,
    "qty": 2,
    "location": "Swastika Bungalow",
    "tl": "Pak Usman",
    "status": "Finish",
    "modems": "NET24, NET25",
    "invoice_status": "Paid",
    "remark": "Bali & Lombok"
  },
  {
    "tourcode": "BAT220716R",
    "start_date": "17-Jul-2022",
    "end_date": "28-Jul-2022",
    "days": 12,
    "qty": 1,
    "location": "Champlung Sari Ubud",
    "tl": "Nino Sumdap",
    "status": "Finish",
    "modems": "NET10",
    "invoice_status": "Paid",
    "remark": "Champlung Sari"
  },
  {
    "tourcode": "FIS220716P",
    "start_date": "17-Jul-2022",
    "end_date": "04-Aug-2022",
    "days": 19,
    "qty": 3,
    "location": "Le Polonia Hotel Medan",
    "tl": "Chairul Effendi",
    "status": "Finish",
    "modems": "MC1, MC2, MC3",
    "invoice_status": "Paid",
    "remark": "Book by Bu Peri, Kirim tanggal 13 Jul.22"
  },
  {
    "tourcode": "FIO220723P",
    "start_date": "24-Jul-2022",
    "end_date": "04-Aug-2022",
    "days": 12,
    "qty": 1,
    "location": "Champlung Sari Ubud",
    "tl": "Andi Kurniawan",
    "status": "Finish",
    "modems": "NET22",
    "invoice_status": "Paid",
    "remark": "Bali Lombok"
  },
  {
    "tourcode": "SOD220730V",
    "start_date": "31-Jul-2022",
    "end_date": "11-Aug-2022",
    "days": 12,
    "qty": 1,
    "location": "Sri Phala Resort And Villa",
    "tl": "Pak Usman",
    "status": "Finish",
    "modems": "NET25",
    "invoice_status": "Paid",
    "remark": "Bali only"
  },
  {
    "tourcode": "KIB220730C",
    "start_date": "31-Jul-2022",
    "end_date": "11-Aug-2022",
    "days": 12,
    "qty": 5,
    "location": "Bhuwana Ubud",
    "tl": "Gede Suadnyana",
    "status": "Finish",
    "modems": "NET02, NET03, NET04, NET05, NET07",
    "invoice_status": "Paid",
    "remark": "Bali only"
  },
  {
    "tourcode": "BAT220730",
    "start_date": "31-Jul-2022",
    "end_date": "11-Aug-2022",
    "days": 12,
    "qty": 1,
    "location": "Champlung Sari Ubud",
    "tl": "Nino Sumendap",
    "status": "Finish",
    "modems": "NET09",
    "invoice_status": "Paid",
    "remark": "Bali Banyuwangi"
  },
  {
    "tourcode": "FIO220813B",
    "start_date": "14-Aug-2022",
    "end_date": "25-Aug-2022",
    "days": 13,
    "qty": 3,
    "location": "Sri Aksata Ubud",
    "tl": "Yance",
    "status": "Finish",
    "modems": "NET13, NET14, NET15",
    "invoice_status": "Paid",
    "remark": "Bali only"
  },
  {
    "tourcode": "SOO220813V",
    "start_date": "14-Aug-2022",
    "end_date": "25-Aug-2022",
    "days": 12,
    "qty": 2,
    "location": "Swastika Bungalow",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "NET02, NET03",
    "invoice_status": "Paid",
    "remark": "Bali only"
  },
  {
    "tourcode": "SOO220903S",
    "start_date": "04-Sep-2022",
    "end_date": "15-Sep-2022",
    "days": 12,
    "qty": 3,
    "location": "Swastika Bungalow",
    "tl": "Agus Wiraman",
    "status": "Finish",
    "modems": "NET04, NET05, NET10",
    "invoice_status": "Paid",
    "remark": "Bali Lombok"
  },
  {
    "tourcode": "SOJ220908S",
    "start_date": "09-Sep-2022",
    "end_date": "28-Sep-2022",
    "days": 20,
    "qty": 8,
    "location": "Favehotel Tanah Abang Cideng",
    "tl": "Empong Kuswoyo",
    "status": "Finish",
    "modems": "NET01, NET02, NET03, NET16, NET17, NET18, NET19, NET20",
    "invoice_status": "Paid",
    "remark": "Jawa & Bali, tamu minta diskon"
  },
  {
    "tourcode": "SOO220910",
    "start_date": "11-Sep-2022",
    "end_date": "22-Sep-2022",
    "days": 12,
    "qty": 1,
    "location": "Swastika Bungalow",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "NET15",
    "invoice_status": "Paid",
    "remark": "Bali Lombok"
  },
  {
    "tourcode": "BAT220910",
    "start_date": "11-Sep-2022",
    "end_date": "22-Sep-2022",
    "days": 12,
    "qty": 1,
    "location": "Sri Aksata Ubud",
    "tl": "Sofyan Manik",
    "status": "Finish",
    "modems": "NET14",
    "invoice_status": "Paid",
    "remark": "bali & Java"
  },
  {
    "tourcode": "BAS220916",
    "start_date": "17-Sep-2022",
    "end_date": "06-Oct-2022",
    "days": 20,
    "qty": 6,
    "location": "Swastika Bungalow",
    "tl": "Komang Karung",
    "status": "Finish",
    "modems": "NET04, NET05, NET06, NET10, NET21, NET25",
    "invoice_status": "Paid",
    "remark": "Bali, NTB, NTT"
  },
  {
    "tourcode": "BAI220917",
    "start_date": "18-Sep-2022",
    "end_date": "06-Oct-2022",
    "days": 19,
    "qty": 3,
    "location": "Le Polonia Hotel",
    "tl": "Linda Samosir",
    "status": "Finish",
    "modems": "NET07, NET08, NET09",
    "invoice_status": "Paid",
    "remark": "Sumatra, Java & Bali"
  },
  {
    "tourcode": "SOD220924S",
    "start_date": "25-Sep-2022",
    "end_date": "06-Oct-2022",
    "days": 12,
    "qty": 7,
    "location": "Sri Phala Resort And Villa",
    "tl": "Ayu Putu",
    "status": "Finish",
    "modems": "NET12, NET13, NET14, NET15, NET17, NET22, NET23",
    "invoice_status": "Paid",
    "remark": "Bali only"
  },
  {
    "tourcode": "AIS221014R",
    "start_date": "15-Oct-2022",
    "end_date": "03-Nov-2022",
    "days": 20,
    "qty": 2,
    "location": "Swastika Bungalow",
    "tl": "Komang Merta",
    "status": "Finish",
    "modems": "NET16, NET19",
    "invoice_status": "Paid",
    "remark": "Bali, NTB, NTT (30GB)"
  },
  {
    "tourcode": "SOD221022S",
    "start_date": "23-Oct-2022",
    "end_date": "03-Nov-2022",
    "days": 12,
    "qty": 6,
    "location": "Sri Phala Resort And Villa",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "NET10, NET11, NET12, NET13, NET15, NET18",
    "invoice_status": "Paid",
    "remark": "Bali only"
  },
  {
    "tourcode": "AIT221022",
    "start_date": "23-Oct-2022",
    "end_date": "03-Nov-2022",
    "days": 12,
    "qty": 1,
    "location": "Sri Aksata Ubud",
    "tl": "Yance",
    "status": "Finish",
    "modems": "NET14",
    "invoice_status": "Paid",
    "remark": "bali & Java (30GB)"
  },
  {
    "tourcode": "SOJ221103T",
    "start_date": "04-Nov-2022",
    "end_date": "23-Nov-2022",
    "days": 20,
    "qty": 3,
    "location": "Favehotel Tanah Abang Cideng",
    "tl": "Evy",
    "status": "Finish",
    "modems": "NET01, NET02, NET03",
    "invoice_status": "Paid",
    "remark": "Java, Bali, Gili Island (dibawa tamu net03)"
  },
  {
    "tourcode": "BAT221105R",
    "start_date": "06-Nov-2022",
    "end_date": "17-Nov-2022",
    "days": 12,
    "qty": 4,
    "location": "Sri Aksata Ubud",
    "tl": "Nino Sumendap",
    "status": "Finish",
    "modems": "NET05, NET06, NET07, NET08",
    "invoice_status": "Paid",
    "remark": "Bali Jawa"
  },
  {
    "tourcode": "SOO221112",
    "start_date": "13-Nov-2022",
    "end_date": "24-Nov-2022",
    "days": 12,
    "qty": 4,
    "location": "Swastika Bungalow",
    "tl": "Pendot",
    "status": "Finish",
    "modems": "NET11, NET12, NET13, NET15",
    "invoice_status": "Paid",
    "remark": "Bali Lombok Complete"
  },
  {
    "tourcode": "SOO221119V",
    "start_date": "20-Nov-2022",
    "end_date": "01-Dec-2022",
    "days": 12,
    "qty": 6,
    "location": "Swastika Bungalow",
    "tl": "Agus Wiraman",
    "status": "Finish",
    "modems": "NET05, NET06, NET07, NET08, NET16, NET19",
    "invoice_status": "Paid",
    "remark": "Bali Lombok"
  },
  {
    "tourcode": "SOD221224",
    "start_date": "25-Dec-2022",
    "end_date": "06-Jan-2023",
    "days": 13,
    "qty": 3,
    "location": "Sri Phala Resort And Villa",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "NET04, NET05, NET12",
    "invoice_status": "Paid",
    "remark": "Bali Tour"
  },
  {
    "tourcode": "FIO221224B",
    "start_date": "25-Dec-2022",
    "end_date": "06-Jan-2023",
    "days": 13,
    "qty": 2,
    "location": "Champlung Sari Ubud",
    "tl": "Gede Suadnyana",
    "status": "Finish",
    "modems": "NET01, NET02",
    "invoice_status": "Paid",
    "remark": "Bali Lombok"
  },
  {
    "tourcode": "AIS230211R",
    "start_date": "12-Feb-2023",
    "end_date": "02-Mar-2023",
    "days": 19,
    "qty": 2,
    "location": "Swastika Bungalow",
    "tl": "Komang Karung",
    "status": "Finish",
    "modems": "NET02, NET04",
    "invoice_status": "Paid",
    "remark": "Bali, NTB, NTT"
  },
  {
    "tourcode": "SOD230318T",
    "start_date": "19-Mar-2023",
    "end_date": "31-Mar-2023",
    "days": 13,
    "qty": 2,
    "location": "Sanur, Bali",
    "tl": "Ayu Putu",
    "status": "Finish",
    "modems": "NET04, NET05",
    "invoice_status": "Paid",
    "remark": "Bali only"
  },
  {
    "tourcode": "BAT230401",
    "start_date": "02-Apr-2023",
    "end_date": "14-Apr-2023",
    "days": 13,
    "qty": 2,
    "location": "Sri Aksata Ubud",
    "tl": "Gede Sentana",
    "status": "Finish",
    "modems": "NET01, NET02",
    "invoice_status": "Paid",
    "remark": "Ubud, Bali"
  },
  {
    "tourcode": "FIO230422B",
    "start_date": "23-Apr-2023",
    "end_date": "05-May-2023",
    "days": 13,
    "qty": 1,
    "location": "Swastika Bungalow",
    "tl": "Yance",
    "status": "Finish",
    "modems": "NET02",
    "invoice_status": "Paid",
    "remark": "Bali Lombok"
  },
  {
    "tourcode": "SOO230422S",
    "start_date": "23-Apr-2023",
    "end_date": "05-May-2023",
    "days": 13,
    "qty": 6,
    "location": "Sanur, Bali",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "NET05, NET06, NET09, NET10, NET11, NET21",
    "invoice_status": "Paid",
    "remark": "Bali Lombok"
  },
  {
    "tourcode": "FIB230422",
    "start_date": "23-Apr-2023",
    "end_date": "06-May-2023",
    "days": 14,
    "qty": 1,
    "location": "Bhuwana Ubud",
    "tl": "Andi Kurniawan",
    "status": "Finish",
    "modems": "NET04",
    "invoice_status": "Paid",
    "remark": "Bali Lombok"
  },
  {
    "tourcode": "SOJ230511",
    "start_date": "12-May-2023",
    "end_date": "31-May-2023",
    "days": 20,
    "qty": 1,
    "location": "Jakarta",
    "tl": "Evy",
    "status": "Finish",
    "modems": "NET09",
    "invoice_status": "Paid",
    "remark": "Java, Bali en Gili eilanden"
  },
  {
    "tourcode": "SOO230513",
    "start_date": "14-May-2023",
    "end_date": "26-May-2023",
    "days": 13,
    "qty": 2,
    "location": "Swastika Bungalow",
    "tl": "Pendot",
    "status": "Finish",
    "modems": "NET11, NET21",
    "invoice_status": "Paid",
    "remark": "Bali en Lombok"
  },
  {
    "tourcode": "AIS230513R",
    "start_date": "14-May-2023",
    "end_date": "01-Jun-2023",
    "days": 19,
    "qty": 5,
    "location": "Swastika Bungalow",
    "tl": "Komang Karung",
    "status": "Finish",
    "modems": "NET01, NET02, NET04, NET05, NET06",
    "invoice_status": "Paid",
    "remark": "Rondreis Sunda Eilanden"
  },
  {
    "tourcode": "SOJ230525V",
    "start_date": "26-May-2023",
    "end_date": "14-Jun-2023",
    "days": 20,
    "qty": 8,
    "location": "Erian Hotel Jakarta",
    "tl": "Empong Kuswoyo",
    "status": "Finish",
    "modems": "NET12, NET14, NET15, NET16, NET18, NET19, NET20, NET22",
    "invoice_status": "Paid",
    "remark": "Java, Bali en Gili eilanden (Keep monitoring)"
  },
  {
    "tourcode": "SOO230527V",
    "start_date": "28-May-2023",
    "end_date": "09-Jun-2023",
    "days": 13,
    "qty": 5,
    "location": "Swastika Bungalow",
    "tl": "Pendot",
    "status": "Finish",
    "modems": "NET10, NET11, NET17, NET21, NET25",
    "invoice_status": "Paid",
    "remark": "Bali en Lombok"
  },
  {
    "tourcode": "AIN230609",
    "start_date": "10-Jun-2023",
    "end_date": "29-Jun-2023",
    "days": 20,
    "qty": 5,
    "location": "Sumatra",
    "tl": "Linda Samosir",
    "status": "Finish",
    "modems": "NET01, NET02, NET04, NET05, NET06",
    "invoice_status": "Paid",
    "remark": "Rondreis Sumatra, Java en Bali"
  },
  {
    "tourcode": "AIS230610R",
    "start_date": "11-Jun-2023",
    "end_date": "29-Jun-2023",
    "days": 19,
    "qty": 1,
    "location": "Swastika Bungalow",
    "tl": "Komang Karung",
    "status": "Finish",
    "modems": "NET10",
    "invoice_status": "Paid",
    "remark": "Rondreis Sunda Eilanden"
  },
  {
    "tourcode": "SOJ230615T",
    "start_date": "16-Jun-2023",
    "end_date": "05-Jul-2023",
    "days": 20,
    "qty": 1,
    "location": "Jakarta",
    "tl": "Empong Kuswoyo",
    "status": "Finish",
    "modems": "NET14",
    "invoice_status": "Paid",
    "remark": "bali & Java"
  },
  {
    "tourcode": "SOD230617T",
    "start_date": "18-Jun-2023",
    "end_date": "30-Jun-2023",
    "days": 13,
    "qty": 2,
    "location": "Sri Phala Sanur",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "NET15, NET16",
    "invoice_status": "Paid",
    "remark": "Bali (NET15 20GB, NET16 16GB)"
  },
  {
    "tourcode": "SOO230617T",
    "start_date": "18-Jun-2023",
    "end_date": "30-Jun-2023",
    "days": 13,
    "qty": 2,
    "location": "Swastika Bungalow",
    "tl": "Pendot",
    "status": "Finish",
    "modems": "NET12, NET21",
    "invoice_status": "Paid",
    "remark": "Bali and Lombok (NET12 19GB, NET21 16GB)"
  },
  {
    "tourcode": "BAT230701R",
    "start_date": "02-Jul-2023",
    "end_date": "14-Jul-2023",
    "days": 13,
    "qty": 5,
    "location": "Sri Aksata Ubud",
    "tl": "Nino Sumendap",
    "status": "Finish",
    "modems": "NET17, NET18, NET19, NET20, NET22",
    "invoice_status": "Paid",
    "remark": "Bali en Java (all 28GB)"
  },
  {
    "tourcode": "AIS230707R",
    "start_date": "08-Jul-2023",
    "end_date": "27-Jul-2023",
    "days": 20,
    "qty": 1,
    "location": "Swastika Bungalow",
    "tl": "Komang Karung",
    "status": "Finish",
    "modems": "NET01",
    "invoice_status": "Paid",
    "remark": "Rondreis Sunda Eilanden (25GB)"
  },
  {
    "tourcode": "KIO230708P",
    "start_date": "09-Jul-2023",
    "end_date": "21-Jul-2023",
    "days": 13,
    "qty": 6,
    "location": "Sens Hotel Ubud",
    "tl": "Yance",
    "status": "Finish",
    "modems": "NET05, NET10, NET12, NET14, NET15, NET16, NET20",
    "invoice_status": "Paid",
    "remark": "Familiereis Indonesie: Bali en Lombok"
  },
  {
    "tourcode": "AIT230708R",
    "start_date": "09-Jul-2023",
    "end_date": "21-Jul-2023",
    "days": 13,
    "qty": 1,
    "location": "Sri Aksata Ubud",
    "tl": "Gede Suadnyana",
    "status": "Finish",
    "modems": "NET09",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali en Java"
  },
  {
    "tourcode": "SOO230714S",
    "start_date": "15-Jul-2023",
    "end_date": "27-Jul-2023",
    "days": 13,
    "qty": 5,
    "location": "Swastika Bungalow",
    "tl": "Ayu Putu",
    "status": "Finish",
    "modems": "NET08, NET21, NET11, NET25, MC3",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali en Lombok"
  },
  {
    "tourcode": "FIO230715",
    "start_date": "16-Jul-2023",
    "end_date": "28-Jul-2023",
    "days": 13,
    "qty": 2,
    "location": "B.Saya Villa Ubud",
    "tl": "Nino Sumendap",
    "status": "Finish",
    "modems": "NET17, NET18",
    "invoice_status": "Paid",
    "remark": "Bali en Lombok"
  },
  {
    "tourcode": "FIO230715B",
    "start_date": "16-Jul-2023",
    "end_date": "28-Jul-2023",
    "days": 13,
    "qty": 4,
    "location": "Sens Hotel Ubud",
    "tl": "Andi Kurniawan",
    "status": "Finish",
    "modems": "NET13, NET19, NET22, NET26",
    "invoice_status": "Paid",
    "remark": "Bali en Lombok"
  },
  {
    "tourcode": "FIS230715P",
    "start_date": "16-Jul-2023",
    "end_date": "03-Aug-2023",
    "days": 19,
    "qty": 3,
    "location": "Le Polonia Hotel Medan",
    "tl": "Chairul Effendi",
    "status": "Finish",
    "modems": "NET02, NET04, NET06",
    "invoice_status": "Paid",
    "remark": "Familiereis Indonesie Totaal"
  },
  {
    "tourcode": "FIO230722P",
    "start_date": "23-Jul-2023",
    "end_date": "04-Aug-2023",
    "days": 13,
    "qty": 7,
    "location": "Sens Hotel Ubud",
    "tl": "Gede Suadnyana",
    "status": "Finish",
    "modems": "NET09, NET10, NET12, NET16, NET20, MC13, MC14",
    "invoice_status": "Paid",
    "remark": "Bali en Lombok"
  },
  {
    "tourcode": "FIS230722B",
    "start_date": "23-Jul-2023",
    "end_date": "10-Aug-2023",
    "days": 19,
    "qty": 2,
    "location": "Le Polonia Hotel Medan",
    "tl": "Linda Samosir",
    "status": "Finish",
    "modems": "MC4, MC5",
    "invoice_status": "Paid",
    "remark": "Familiereis Indonesie Totaal"
  },
  {
    "tourcode": "AIS230724",
    "start_date": "25-Jul-2023",
    "end_date": "13-Aug-2023",
    "days": 20,
    "qty": 10,
    "location": "Swastika Bungalow",
    "tl": "Yance",
    "status": "Finish",
    "modems": "MC6, MC7, MC8, MC9, MC10, MC11, MC12, NET14, MC15, MC23",
    "invoice_status": "Paid",
    "remark": "Rondreis Sunda Eilanden"
  },
  {
    "tourcode": "FID230728B",
    "start_date": "29-Jul-2023",
    "end_date": "17-Aug-2023",
    "days": 20,
    "qty": 2,
    "location": "Sukajadi Hotel (Bandung)",
    "tl": "Maureen",
    "status": "Finish",
    "modems": "MC16, MC17",
    "invoice_status": "Paid",
    "remark": "Indonesie Avontuur"
  },
  {
    "tourcode": "SOO230728V",
    "start_date": "29-Jul-2023",
    "end_date": "10-Aug-2023",
    "days": 13,
    "qty": 10,
    "location": "Sriphala Resort & Spa Sanur",
    "tl": "Usman",
    "status": "Finish",
    "modems": "MC3, NET11, NET13, NET17, NET18, NET19, NET21, NET22, NET25, MC26",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali en Lombok"
  },
  {
    "tourcode": "KIB230728B",
    "start_date": "29-Jul-2023",
    "end_date": "10-Aug-2023",
    "days": 13,
    "qty": 2,
    "location": "Bhuwana Hotel Ubud",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "MC1, MC2",
    "invoice_status": "Paid",
    "remark": "Familireis Indonesie Bali Cultur"
  },
  {
    "tourcode": "AIL230728R",
    "start_date": "29-Jul-2023",
    "end_date": "17-Aug-2023",
    "days": 20,
    "qty": 5,
    "location": "Erian Hotel Jakarta",
    "tl": "Sugiarto",
    "status": "Finish",
    "modems": "MC18, MC19, MC20, MC21, MC22",
    "invoice_status": "Paid",
    "remark": "Rondreis Indonesië: Java, Bali en Gili eilanden"
  },
  {
    "tourcode": "KIO230729C",
    "start_date": "30-Jul-2023",
    "end_date": "11-Aug-2023",
    "days": 13,
    "qty": 1,
    "location": "Sens Hotel Ubud",
    "tl": "Agus Wiraman",
    "status": "Finish",
    "modems": "MC9",
    "invoice_status": "Paid",
    "remark": "Familiereis Indonesie: Bali en Lombok"
  },
  {
    "tourcode": "AIN230804R",
    "start_date": "05-Aug-2023",
    "end_date": "24-Aug-2023",
    "days": 20,
    "qty": 1,
    "location": "Le Polonia Hotel Medan",
    "tl": "Nurdin Nasution",
    "status": "Finish",
    "modems": "MC24",
    "invoice_status": "Paid",
    "remark": "Rondreis Sumatra, Java en Bali"
  },
  {
    "tourcode": "SOJ230804S",
    "start_date": "05-Aug-2023",
    "end_date": "24-Aug-2023",
    "days": 20,
    "qty": 5,
    "location": "Favehotel Tanah Abang Cideng",
    "tl": "Arlhian Fahar",
    "status": "Finish",
    "modems": "MC27, MC28, MC29, MC30, MC31",
    "invoice_status": "Paid",
    "remark": "Java, Bali en Gili eilanden"
  },
  {
    "tourcode": "AIL230804",
    "start_date": "05-Aug-2023",
    "end_date": "24-Aug-2023",
    "days": 20,
    "qty": 5,
    "location": "Erian Hotel Jakarta",
    "tl": "Chairul Effendi",
    "status": "Finish",
    "modems": "MC25, MC26, NET02, NET04, NET06",
    "invoice_status": "Paid",
    "remark": "Java, Bali en Gili eilanden"
  },
  {
    "tourcode": "SOD230902T",
    "start_date": "03-Sep-2023",
    "end_date": "15-Sep-2023",
    "days": 13,
    "qty": 2,
    "location": "Sri Phala Sanur",
    "tl": "Ayu Putu",
    "status": "Finish",
    "modems": "MC1, MC2",
    "invoice_status": "Paid",
    "remark": "Bali only"
  },
  {
    "tourcode": "SOO230902S",
    "start_date": "03-Sep-2023",
    "end_date": "15-Sep-2023",
    "days": 13,
    "qty": 5,
    "location": "Abian Harmony Hotel",
    "tl": "Agus Wiraman",
    "status": "Finish",
    "modems": "MC3, MC4, MC5, MC6, MC7",
    "invoice_status": "Paid",
    "remark": "Bali en Lombok"
  },
  {
    "tourcode": "SOJ230907T",
    "start_date": "08-Sep-2023",
    "end_date": "27-Sep-2023",
    "days": 20,
    "qty": 7,
    "location": "Favehotel Tanah Abang Cideng",
    "tl": "Empong Kuswoyo",
    "status": "Finish",
    "modems": "MC8, MC9, MC10, MC11, MC12, MC13, MC14",
    "invoice_status": "Paid",
    "remark": "Indonesie: Java, Bali en Gili eilanden"
  },
  {
    "tourcode": "AIL230907R",
    "start_date": "08-Sep-2023",
    "end_date": "27-Sep-2023",
    "days": 20,
    "qty": 2,
    "location": "Erian Hotel Jakarta",
    "tl": "Edy Suryawan",
    "status": "Finish",
    "modems": "MC15, MC16",
    "invoice_status": "Paid",
    "remark": "Rondreis Indonesië: Java, Bali en Gili eilanden"
  },
  {
    "tourcode": "SOD230909V",
    "start_date": "10-Sep-2023",
    "end_date": "22-Sep-2023",
    "days": 13,
    "qty": 8,
    "location": "Sri Phala Resort And Villa",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "MC17, MC18, MC19, MC20, MC21, MC22, MC23, MC29",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali"
  },
  {
    "tourcode": "BAT230909R",
    "start_date": "10-Sep-2023",
    "end_date": "22-Sep-2023",
    "days": 13,
    "qty": 1,
    "location": "Sri Aksata Ubud",
    "tl": "Gede Suadnyana",
    "status": "Finish",
    "modems": "MC25",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali en Java - Ms. Emma Stas"
  },
  {
    "tourcode": "AIN230915",
    "start_date": "16-Sep-2023",
    "end_date": "05-Oct-2023",
    "days": 20,
    "qty": 2,
    "location": "Le Polonia Hotel Medan",
    "tl": "Chairul Effendi",
    "status": "Finish",
    "modems": "MC27, MC29",
    "invoice_status": "Paid",
    "remark": "Rondreis Sumatra, Java en Bali"
  },
  {
    "tourcode": "SSN230916",
    "start_date": "17-Sep-2023",
    "end_date": "05-Oct-2023",
    "days": 19,
    "qty": 2,
    "location": "Sri Aksata Ubud",
    "tl": "Subhan Saputra",
    "status": "Finish",
    "modems": "MC4, MC2",
    "invoice_status": "Paid",
    "remark": "Rondreis Soenda eilanden"
  },
  {
    "tourcode": "SOO230916V",
    "start_date": "17-Sep-2023",
    "end_date": "29-Sep-2023",
    "days": 13,
    "qty": 1,
    "location": "Swastika Bungalow",
    "tl": "Usman",
    "status": "Finish",
    "modems": "MC1",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali en Lombok"
  },
  {
    "tourcode": "BAS230916",
    "start_date": "17-Sep-2023",
    "end_date": "05-Oct-2023",
    "days": 19,
    "qty": 3,
    "location": "Sanur, Bali",
    "tl": "Komang Merta",
    "status": "Finish",
    "modems": "MC28, MC30, MC31",
    "invoice_status": "Paid",
    "remark": "Rondreis Sunda Eilanden"
  },
  {
    "tourcode": "SOD230923S",
    "start_date": "24-Sep-2023",
    "end_date": "06-Oct-2023",
    "days": 13,
    "qty": 6,
    "location": "Sri Phala Sanur",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "MC17, MC19, MC20, MC21, MC22, MC23",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali (satu modem rusak)"
  },
  {
    "tourcode": "SOO230923",
    "start_date": "24-Sep-2023",
    "end_date": "06-Oct-2023",
    "days": 13,
    "qty": 3,
    "location": "Swastika Bungalow",
    "tl": "Pendot",
    "status": "Finish",
    "modems": "MC5, MC6, MC7",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali en Lombok"
  },
  {
    "tourcode": "SOO230930S",
    "start_date": "01-Oct-2023",
    "end_date": "13-Oct-2023",
    "days": 13,
    "qty": 1,
    "location": "Swastika Bungalow",
    "tl": "Agus Wiraman",
    "status": "Finish",
    "modems": "MC30",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali en Lombok"
  },
  {
    "tourcode": "AIL231005",
    "start_date": "06-Oct-2023",
    "end_date": "25-Oct-2023",
    "days": 20,
    "qty": 2,
    "location": "Erian Hotel Jakarta",
    "tl": "Bram Idrus",
    "status": "Finish",
    "modems": "MC3, MC18",
    "invoice_status": "Paid",
    "remark": "Rondreis Indonesië: Java, Bali en Gili eilanden"
  },
  {
    "tourcode": "AIN231006",
    "start_date": "07-Oct-2023",
    "end_date": "26-Oct-2023",
    "days": 20,
    "qty": 2,
    "location": "Le Polonia Hotel Medan",
    "tl": "Chairul Effendi",
    "status": "Finish",
    "modems": "MC27, MC29",
    "invoice_status": "Paid",
    "remark": "Rondreis Sumatra, Java en Bali"
  },
  {
    "tourcode": "SOO231014V",
    "start_date": "15-Oct-2023",
    "end_date": "27-Oct-2023",
    "days": 13,
    "qty": 4,
    "location": "Swastika Bungalow",
    "tl": "Pendot",
    "status": "Finish",
    "modems": "MC4, MC5, MC27, MC28",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali en Lombok"
  },
  {
    "tourcode": "AIS231014R",
    "start_date": "15-Oct-2023",
    "end_date": "02-Nov-2023",
    "days": 19,
    "qty": 4,
    "location": "Swastika Bungalow",
    "tl": "Komang Karung",
    "status": "Finish",
    "modems": "MC6, MC7, MC8, MC9",
    "invoice_status": "Paid",
    "remark": "Rondreis Sunda Eilanden"
  },
  {
    "tourcode": "SOD231021S",
    "start_date": "22-Oct-2023",
    "end_date": "03-Nov-2023",
    "days": 13,
    "qty": 2,
    "location": "Sri Phala Sanur",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "MC22, MC23",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali (satu modem rusak)"
  },
  {
    "tourcode": "BAI231103",
    "start_date": "04-Nov-2023",
    "end_date": "23-Nov-2023",
    "days": 20,
    "qty": 1,
    "location": "Le Polonia Hotel Medan",
    "tl": "Bram Idrus",
    "status": "Finish",
    "modems": "MC3",
    "invoice_status": "Paid",
    "remark": "Rondreis Sumatra, Java en Bali"
  },
  {
    "tourcode": "SOD231118V",
    "start_date": "19-Nov-2023",
    "end_date": "01-Dec-2023",
    "days": 13,
    "qty": 5,
    "location": "Sri Phala Sanur",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "MC1, MC6, MC8, MC10, MC24",
    "invoice_status": "Paid",
    "remark": "Bali (cek kuota tgl 25 nov)"
  },
  {
    "tourcode": "SOO231209V",
    "start_date": "10-Dec-2023",
    "end_date": "22-Dec-2023",
    "days": 13,
    "qty": 3,
    "location": "Swastika Bungalow",
    "tl": "Pendot",
    "status": "Finish",
    "modems": "MC2, MC7, MC9",
    "invoice_status": "Paid",
    "remark": "Bali en Lombok"
  },
  {
    "tourcode": "SOD231223T",
    "start_date": "24-Dec-2023",
    "end_date": "05-Jan-2024",
    "days": 13,
    "qty": 4,
    "location": "Sriphala Resort & Spa Sanur",
    "tl": "Ayu Putu",
    "status": "Finish",
    "modems": "MC1, MC6, MC8, MC10",
    "invoice_status": "Paid",
    "remark": "Bali Tour"
  },
  {
    "tourcode": "SOO231223",
    "start_date": "24-Dec-2023",
    "end_date": "05-Jan-2024",
    "days": 13,
    "qty": 2,
    "location": "Bhumas Sanur",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "MC4, MC5",
    "invoice_status": "Paid",
    "remark": "Bali en Lombok"
  },
  {
    "tourcode": "FIB231223B",
    "start_date": "24-Dec-2023",
    "end_date": "05-Jan-2024",
    "days": 13,
    "qty": 2,
    "location": "Sri Aksata Ubud",
    "tl": "Gede Suadnyana",
    "status": "Finish",
    "modems": "MC11, MC12",
    "invoice_status": "Paid",
    "remark": "Indonesie Bali Cultuur & Strand"
  },
  {
    "tourcode": "BAT231223",
    "start_date": "24-Dec-2023",
    "end_date": "05-Jan-2024",
    "days": 13,
    "qty": 10,
    "location": "Sri Aksata Ubud",
    "tl": "Komang Karung",
    "status": "Finish",
    "modems": "MC13, MC16, MC18, MC19, MC20, MC22, MC23, MC26, MC28, MC29",
    "invoice_status": "Paid",
    "remark": "Bali en Java"
  },
  {
    "tourcode": "AIS240210R",
    "start_date": "11-Feb-2024",
    "end_date": "01-Mar-2024",
    "days": 20,
    "qty": 1,
    "location": "Swastika Bungalow",
    "tl": "Komang Karung",
    "status": "Finish",
    "modems": "MC7",
    "invoice_status": "Paid",
    "remark": "Rondreis Sunda Eilanden"
  },
  {
    "tourcode": "SOJ240307S",
    "start_date": "08-Mar-2024",
    "end_date": "27-Mar-2024",
    "days": 20,
    "qty": 5,
    "location": "Erian Hotel Jakarta",
    "tl": "Empong Kuswoyo",
    "status": "Finish",
    "modems": "MC1, MC2, MC6, MC7, MC8",
    "invoice_status": "Paid",
    "remark": "Java, Bali & Lombok"
  },
  {
    "tourcode": "FIO240420C",
    "start_date": "21-Apr-2024",
    "end_date": "03-May-2024",
    "days": 13,
    "qty": 6,
    "location": "B.Saya Villa Ubud",
    "tl": "Pak Yance",
    "status": "Finish",
    "modems": "MC1, MC2, MC6, MC7, MC8, MC24",
    "invoice_status": "Paid",
    "remark": "Bali & Lombok"
  },
  {
    "tourcode": "AIS240422",
    "start_date": "23-Apr-2024",
    "end_date": "12-May-2024",
    "days": 20,
    "qty": 3,
    "location": "Swastika Bungalow",
    "tl": "Komang Karung",
    "status": "Finish",
    "modems": "MC3, MC4, MC5",
    "invoice_status": "Paid",
    "remark": "Rondreis Sunda Eilanden"
  },
  {
    "tourcode": "SOD240429S",
    "start_date": "30-Apr-2024",
    "end_date": "12-May-2024",
    "days": 13,
    "qty": 4,
    "location": "Sri Phala Sanur",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "MC11, MC12, MC14, MC16",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali"
  },
  {
    "tourcode": "SOO240429V",
    "start_date": "30-Apr-2024",
    "end_date": "12-May-2024",
    "days": 13,
    "qty": 6,
    "location": "Swastika Bungalow",
    "tl": "Subhan Saputra",
    "status": "Finish",
    "modems": "MC26, MC27, MC28, MC29, MC30, MC31",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali en Lombok"
  },
  {
    "tourcode": "AIT240429",
    "start_date": "30-Apr-2024",
    "end_date": "12-May-2024",
    "days": 13,
    "qty": 7,
    "location": "Sri Aksata Ubud",
    "tl": "Nino Sumendap",
    "status": "Finish",
    "modems": "MC10, MC18, MC19, MC20, MC21, MC23, MC25",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali en Java"
  },
  {
    "tourcode": "AIL240509",
    "start_date": "10-May-2024",
    "end_date": "29-May-2024",
    "days": 20,
    "qty": 5,
    "location": "Erian Hotel Jakarta",
    "tl": "Bram Idrus",
    "status": "Finish",
    "modems": "MC1, MC2, MC6, MC7, MC8",
    "invoice_status": "Paid",
    "remark": "Rondreis Indonesië: Java, Bali en Gili eilanden"
  },
  {
    "tourcode": "AIN240510R",
    "start_date": "11-May-2024",
    "end_date": "30-May-2024",
    "days": 20,
    "qty": 2,
    "location": "Le Polonia Hotel Medan",
    "tl": "Chairul Effendi",
    "status": "Finish",
    "modems": "MC17, MC24",
    "invoice_status": "Paid",
    "remark": "Rondreis Sumatra, Java en Bali"
  },
  {
    "tourcode": "SOD240511V",
    "start_date": "12-May-2024",
    "end_date": "24-May-2024",
    "days": 13,
    "qty": 8,
    "location": "Sri Phala Sanur",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "MC11, MC12, MC14, MC16, MC26, MC27, MC28, MC29",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali"
  },
  {
    "tourcode": "SSN240513S",
    "start_date": "14-May-2024",
    "end_date": "02-Jun-2024",
    "days": 20,
    "qty": 3,
    "location": "Puri Padi (Ubud)",
    "tl": "Komang Karung",
    "status": "Finish",
    "modems": "MC3, MC4, MC5",
    "invoice_status": "Paid",
    "remark": "Rondreis Soenda eilanden"
  },
  {
    "tourcode": "SOJ240523V",
    "start_date": "24-May-2024",
    "end_date": "12-Jun-2024",
    "days": 20,
    "qty": 5,
    "location": "Erian Hotel Jakarta",
    "tl": "Empong Kuswoyo",
    "status": "Finish",
    "modems": "MC9, MC10, MC18, MC20, MC30",
    "invoice_status": "Paid",
    "remark": "Java, Bali en Gili eilanden"
  },
  {
    "tourcode": "SOD240526",
    "start_date": "27-May-2024",
    "end_date": "08-Jun-2024",
    "days": 13,
    "qty": 4,
    "location": "Sri Phala Sanur",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "MC11, MC12, MC13, MC14",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali"
  },
  {
    "tourcode": "SOO240526S",
    "start_date": "27-May-2024",
    "end_date": "08-Jun-2024",
    "days": 13,
    "qty": 9,
    "location": "Swastika Bungalow",
    "tl": "Pendot",
    "status": "Finish",
    "modems": "MC16, MC19, MC21, MC23, MC25, MC26, MC27, MC28, MC29",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali en Lombok"
  },
  {
    "tourcode": "AIN240607",
    "start_date": "08-Jun-2024",
    "end_date": "27-Jun-2024",
    "days": 20,
    "qty": 3,
    "location": "Le Polonia Hotel Medan",
    "tl": "Chairul Effendi",
    "status": "Finish",
    "modems": "MC1, MC6, MC24",
    "invoice_status": "Paid",
    "remark": "Rondreis Sumatra, Java en Bali"
  },
  {
    "tourcode": "SOJ240613T",
    "start_date": "14-Jun-2024",
    "end_date": "03-Jul-2024",
    "days": 20,
    "qty": 3,
    "location": "Erian Hotel Jakarta",
    "tl": "Empong Kuswoyo",
    "status": "Finish",
    "modems": "MC9, MC10, MC18",
    "invoice_status": "Paid",
    "remark": "Indonesie: Java, Bali en Gili eilanden"
  },
  {
    "tourcode": "AIL240613",
    "start_date": "14-Jun-2024",
    "end_date": "03-Jul-2024",
    "days": 20,
    "qty": 5,
    "location": "Jambuluwuk Thamrin Hotel Jakarta",
    "tl": "Bram Idrus",
    "status": "Finish",
    "modems": "MC3, MC4, MC5, MC17, MC31",
    "invoice_status": "Paid",
    "remark": "Rondreis Indonesië: Java, Bali en Gili eilanden"
  },
  {
    "tourcode": "SOD240622S",
    "start_date": "23-Jun-2024",
    "end_date": "05-Jul-2024",
    "days": 13,
    "qty": 6,
    "location": "Sri Phala Sanur",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "MC2, MC7, MC8, MC11, MC12, MC13",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali"
  },
  {
    "tourcode": "SOO240622T",
    "start_date": "23-Jun-2024",
    "end_date": "05-Jul-2024",
    "days": 13,
    "qty": 6,
    "location": "Swastika Bungalow",
    "tl": "Pendot",
    "status": "Finish",
    "modems": "MC16, MC19, MC23, MC25, MC28, MC30",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali en Lombok"
  },
  {
    "tourcode": "SOD240706V",
    "start_date": "07-Jul-2024",
    "end_date": "19-Jul-2024",
    "days": 13,
    "qty": 4,
    "location": "Sri Phala Sanur",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "MC16, MC23, MC28, MC29",
    "invoice_status": "Paid",
    "remark": "Sanur Bali"
  },
  {
    "tourcode": "KIO240706B",
    "start_date": "07-Jul-2024",
    "end_date": "19-Jul-2024",
    "days": 13,
    "qty": 1,
    "location": "Sens Hotel Ubud",
    "tl": "Gede Suadnyana",
    "status": "Finish",
    "modems": "MC25",
    "invoice_status": "Paid",
    "remark": "Sens Hotel Ubud"
  },
  {
    "tourcode": "FIS240709B",
    "start_date": "10-Jul-2024",
    "end_date": "29-Jul-2024",
    "days": 20,
    "qty": 3,
    "location": "Le Polonia Hotel Medan",
    "tl": "Nurdin Nasution",
    "status": "Finish",
    "modems": "MC1, MC6, MC24",
    "invoice_status": "Paid",
    "remark": "Familiereis Indonesie Totaal"
  },
  {
    "tourcode": "FIO240710C",
    "start_date": "11-Jul-2024",
    "end_date": "23-Jul-2024",
    "days": 13,
    "qty": 2,
    "location": "Sens Hotel Ubud",
    "tl": "Pak Yance",
    "status": "Finish",
    "modems": "MC9, MC10",
    "invoice_status": "Paid",
    "remark": "Familiereis Indonesie: Bali en Lombok"
  },
  {
    "tourcode": "BAJ240711R",
    "start_date": "12-Jul-2024",
    "end_date": "31-Jul-2024",
    "days": 20,
    "qty": 1,
    "location": "Jambuluwuk Thamrin Jakarta",
    "tl": "Bram Idrus",
    "status": "Finish",
    "modems": "MC7",
    "invoice_status": "Paid",
    "remark": "Rondreis Indonesië: Java, Bali en Gili eilanden"
  },
  {
    "tourcode": "FIO240713P",
    "start_date": "14-Jul-2024",
    "end_date": "26-Jul-2024",
    "days": 13,
    "qty": 4,
    "location": "Sens Hotel Ubud",
    "tl": "Hendra Limadarma",
    "status": "Finish",
    "modems": "MC2, MC3, MC4, MC5",
    "invoice_status": "Paid",
    "remark": "Familiereis Indonesie: Bali en Lombok"
  },
  {
    "tourcode": "SOO240713S",
    "start_date": "14-Jul-2024",
    "end_date": "26-Jul-2024",
    "days": 13,
    "qty": 5,
    "location": "Swastika Bungalow",
    "tl": "Pendot",
    "status": "Finish",
    "modems": "MC17, MC18, MC19, MC20, MC21",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali en Lombok"
  },
  {
    "tourcode": "AIN240716",
    "start_date": "17-Jul-2024",
    "end_date": "05-Aug-2024",
    "days": 20,
    "qty": 2,
    "location": "Le Polonia Hotel Medan",
    "tl": "Chairul Effendi",
    "status": "Finish",
    "modems": "MC12, MC13",
    "invoice_status": "Paid",
    "remark": "Rondreis Sumatra, Java en Bali (sent to pak arfan)"
  },
  {
    "tourcode": "AIS240716",
    "start_date": "17-Jul-2024",
    "end_date": "05-Aug-2024",
    "days": 20,
    "qty": 3,
    "location": "Sri Phala Resort And Villa",
    "tl": "Komang Karung",
    "status": "Finish",
    "modems": "MC34, MC35, MC36",
    "invoice_status": "Paid",
    "remark": "Rondreis Sunda Eilanden"
  },
  {
    "tourcode": "SOD240717S",
    "start_date": "18-Jul-2024",
    "end_date": "30-Jul-2024",
    "days": 13,
    "qty": 5,
    "location": "Bumas Hotel Sanur",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "MC1, MC2, MC3, MC4, MC5",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali"
  },
  {
    "tourcode": "BAT240717",
    "start_date": "18-Jul-2024",
    "end_date": "30-Jul-2024",
    "days": 13,
    "qty": 5,
    "location": "Sri Aksata Ubud",
    "tl": "Nino Sumendap",
    "status": "Finish",
    "modems": "MC6, MC7, MC8, MC9, MC10",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali en Java"
  },
  {
    "tourcode": "FID240718B",
    "start_date": "19-Jul-2024",
    "end_date": "07-Aug-2024",
    "days": 20,
    "qty": 4,
    "location": "de Braga by ARTOTEL Bandung",
    "tl": "Sugiarto",
    "status": "Finish",
    "modems": "MC8, MC11, MC14, MC26",
    "invoice_status": "Paid",
    "remark": "Indonesie Avontuur (modem sent)"
  },
  {
    "tourcode": "AIL240718",
    "start_date": "19-Jul-2024",
    "end_date": "07-Aug-2024",
    "days": 20,
    "qty": 3,
    "location": "Jambuluwuk Thamrin Hotel Jakarta",
    "tl": "Padang Suwantoro",
    "status": "Finish",
    "modems": "MC27, MC31, MC32",
    "invoice_status": "Paid",
    "remark": "Rondreis Indonesië: Java, Bali en Gili eilanden (modem sent)"
  },
  {
    "tourcode": "SOO240720V",
    "start_date": "21-Jul-2024",
    "end_date": "20-Aug-2024",
    "days": 30,
    "qty": 5,
    "location": "Sri Phala Resort And Villa",
    "tl": "Ell Pratama",
    "status": "Finish",
    "modems": "MC16, MC23, MC25, MC28, MC29",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali en Lombok"
  },
  {
    "tourcode": "KIO240724",
    "start_date": "25-Jul-2024",
    "end_date": "06-Aug-2024",
    "days": 13,
    "qty": 4,
    "location": "Sens Hotel Ubud",
    "tl": "Gede Suadnyana",
    "status": "Finish",
    "modems": "MC7, MC8, MC12, MC15",
    "invoice_status": "Paid",
    "remark": "Familiereis Indonesie: Bali en Lombok (Mussche Family, Wittenberg Family)"
  },
  {
    "tourcode": "FID240725C",
    "start_date": "26-Jul-2024",
    "end_date": "14-Aug-2024",
    "days": 20,
    "qty": 2,
    "location": "de Braga by ARTOTEL Bandung",
    "tl": "Yovi Trisna",
    "status": "Finish",
    "modems": "MC33, NET11",
    "invoice_status": "Paid",
    "remark": "Indonesie Avontuur"
  },
  {
    "tourcode": "AIL240725R",
    "start_date": "26-Jul-2024",
    "end_date": "14-Aug-2024",
    "days": 20,
    "qty": 6,
    "location": "Erian Hotel Jakarta",
    "tl": "Empong Kuswoyo",
    "status": "Finish",
    "modems": "MC1, MC2, MC3, MC4, MC5, NET17",
    "invoice_status": "Paid",
    "remark": "Rondreis Indonesië: Java, Bali en Gili eilanden"
  },
  {
    "tourcode": "FIO240727B",
    "start_date": "28-Jul-2024",
    "end_date": "09-Aug-2024",
    "days": 13,
    "qty": 2,
    "location": "Sri Aksata Ubud",
    "tl": "Pak Yance",
    "status": "Finish",
    "modems": "MC4, MC5",
    "invoice_status": "Paid",
    "remark": "Familiereis Indonesie: Bali en Lombok"
  },
  {
    "tourcode": "AIS240730R",
    "start_date": "31-Jul-2024",
    "end_date": "19-Aug-2024",
    "days": 20,
    "qty": 1,
    "location": "Sri Aksata Ubud",
    "tl": "Subhan Saputra",
    "status": "Finish",
    "modems": "MC24",
    "invoice_status": "Paid",
    "remark": "Familiereis Indonesie Totaal"
  },
  {
    "tourcode": "FIS240730P",
    "start_date": "31-Jul-2024",
    "end_date": "19-Aug-2024",
    "days": 20,
    "qty": 1,
    "location": "Le Polonia Hotel Medan",
    "tl": "Linda Samosir",
    "status": "Finish",
    "modems": "MC2",
    "invoice_status": "Paid",
    "remark": "Le Polonial"
  },
  {
    "tourcode": "FIO240731C",
    "start_date": "01-Aug-2024",
    "end_date": "13-Aug-2024",
    "days": 13,
    "qty": 1,
    "location": "Sens Hotel Ubud",
    "tl": "Pendot",
    "status": "Finish",
    "modems": "MC6",
    "invoice_status": "Paid",
    "remark": "Sens Hotel Ubud"
  },
  {
    "tourcode": "SOO240731S",
    "start_date": "01-Aug-2024",
    "end_date": "13-Aug-2024",
    "days": 13,
    "qty": 6,
    "location": "Swastika Bungalow",
    "tl": "Pak Usman",
    "status": "Finish",
    "modems": "MC20, MC35, NET1, NET2, NET3, NET8",
    "invoice_status": "Paid",
    "remark": "Lombok, Indonesie: Bali en Lombok"
  },
  {
    "tourcode": "BAT240731",
    "start_date": "01-Aug-2024",
    "end_date": "13-Aug-2024",
    "days": 13,
    "qty": 1,
    "location": "Sri Aksata Ubud",
    "tl": "Widi Astuti",
    "status": "Finish",
    "modems": "MC1",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali en Java"
  },
  {
    "tourcode": "FID240801P",
    "start_date": "02-Aug-2024",
    "end_date": "21-Aug-2024",
    "days": 20,
    "qty": 4,
    "location": "de Braga by ARTOTEL Bandung",
    "tl": "Bram Idrus",
    "status": "Finish",
    "modems": "MC17, MC18, MC19, MC21",
    "invoice_status": "Paid",
    "remark": "Indonesie Avontuur (1 Modem dibalikin, sisanya 1o1)"
  },
  {
    "tourcode": "AIL240801R",
    "start_date": "02-Aug-2024",
    "end_date": "21-Aug-2024",
    "days": 20,
    "qty": 1,
    "location": "Jambuluwuk Thamrin Hotel Jakarta",
    "tl": "Halim Karnadi",
    "status": "Finish",
    "modems": "MC3",
    "invoice_status": "Paid",
    "remark": "Jambuluwuk Thamrin"
  },
  {
    "tourcode": "FIO240803P",
    "start_date": "04-Aug-2024",
    "end_date": "16-Aug-2024",
    "days": 13,
    "qty": 4,
    "location": "Sens Hotel Ubud",
    "tl": "Andi Septanto Kurnia",
    "status": "Finish",
    "modems": "MC23, MC25, MC28, MC29",
    "invoice_status": "Paid",
    "remark": "Rubio Pty, DeCoster Pty, Vandendael Pty x2"
  },
  {
    "tourcode": "AIN240806E",
    "start_date": "07-Aug-2024",
    "end_date": "26-Aug-2024",
    "days": 20,
    "qty": 1,
    "location": "Medan, Polonia Hotel",
    "tl": "Komang Karung",
    "status": "Finish",
    "modems": "MC34",
    "invoice_status": "Paid",
    "remark": "Medan Tour"
  },
  {
    "tourcode": "AIN240806",
    "start_date": "07-Aug-2024",
    "end_date": "27-Aug-2024",
    "days": 20,
    "qty": 3,
    "location": "Le Polonia Hotel Medan",
    "tl": "Chairul Effendi",
    "status": "Finish",
    "modems": "MC12, MC13, MC16",
    "invoice_status": "Paid",
    "remark": "Ms. Arfman, Olijslag pty, Ms. DEZUTTERE"
  },
  {
    "tourcode": "FIS240806B",
    "start_date": "07-Aug-2024",
    "end_date": "26-Aug-2024",
    "days": 20,
    "qty": 3,
    "location": "Le Polonia Hotel Medan",
    "tl": "Maureen",
    "status": "Finish",
    "modems": "MC37, MC38, NET06",
    "invoice_status": "Paid",
    "remark": "Sumatra & Bali"
  },
  {
    "tourcode": "FIO240807C",
    "start_date": "08-Aug-2024",
    "end_date": "20-Aug-2024",
    "days": 13,
    "qty": 3,
    "location": "Sens Hotel Ubud",
    "tl": "Nino Sumendap",
    "status": "Finish",
    "modems": "MC10, MC39, MC40",
    "invoice_status": "Paid",
    "remark": "baru dibayar 1, sisa 2"
  },
  {
    "tourcode": "SOO240807V",
    "start_date": "09-Aug-2024",
    "end_date": "20-Aug-2024",
    "days": 12,
    "qty": 5,
    "location": "Swastika Bungalow",
    "tl": "Ell Pratama",
    "status": "Finish",
    "modems": "MC9, MC14, MC27, MC30, MC32",
    "invoice_status": "Paid",
    "remark": "Ms.Uludogan, Mr. Den Boer, Ms. Hummel, Ms. de Jong, Mr. Barneveld"
  },
  {
    "tourcode": "SOJ240808",
    "start_date": "09-Aug-2024",
    "end_date": "28-Aug-2024",
    "days": 20,
    "qty": 2,
    "location": "Erian Hotel Jakarta",
    "tl": "Arlhian Fahar",
    "status": "Finish",
    "modems": "MC11, MC26",
    "invoice_status": "Paid",
    "remark": "Mr. Zijtveld, Pty Dittmar"
  },
  {
    "tourcode": "FID240808C",
    "start_date": "10-Aug-2024",
    "end_date": "28-Aug-2024",
    "days": 19,
    "qty": 1,
    "location": "de Braga by ARTOTEL Bandung",
    "tl": "Sugiarto",
    "status": "Finish",
    "modems": "MC8",
    "invoice_status": "Paid",
    "remark": "Bandung Tour"
  },
  {
    "tourcode": "FIB240810B",
    "start_date": "11-Aug-2024",
    "end_date": "23-Aug-2024",
    "days": 13,
    "qty": 3,
    "location": "Bhuwana Ubud",
    "tl": "Gede Suadnyana",
    "status": "Finish",
    "modems": "MC4, MC31, MC36",
    "invoice_status": "Paid",
    "remark": "1 modem bayar langsung dari TL"
  },
  {
    "tourcode": "SOJ240905V",
    "start_date": "06-Sep-2024",
    "end_date": "25-Sep-2024",
    "days": 20,
    "qty": 10,
    "location": "Erian Hotel Jakarta",
    "tl": "Empong Kuswoyo",
    "status": "Finish",
    "modems": "MC1, MC2, MC3, MC4, MC5, MC6, MC8, MC9, MC10, MC12",
    "invoice_status": "Paid",
    "remark": "Indonesie: Java, Bali en Gili eilanden"
  },
  {
    "tourcode": "BAJ240905R",
    "start_date": "06-Sep-2024",
    "end_date": "25-Sep-2024",
    "days": 20,
    "qty": 4,
    "location": "Jambuluwuk Thamrin Hotel Jakarta",
    "tl": "Bram Idrus",
    "status": "Finish",
    "modems": "MC11, MC13, MC14, MC26",
    "invoice_status": "Paid",
    "remark": "Rondreis Indonesië: Java, Bali en Gili eilanden (2 modem sudah dibawa)"
  },
  {
    "tourcode": "SOD240907T",
    "start_date": "08-Sep-2024",
    "end_date": "20-Sep-2024",
    "days": 13,
    "qty": 4,
    "location": "Sri Phala Sanur",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "MC1, MC2, MC3, MC4",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali"
  },
  {
    "tourcode": "SOO240907S",
    "start_date": "08-Sep-2024",
    "end_date": "20-Sep-2024",
    "days": 13,
    "qty": 3,
    "location": "Swastika Bungalow",
    "tl": "Pendot",
    "status": "Finish",
    "modems": "MC5, MC6, MC7",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali en Lombok"
  },
  {
    "tourcode": "AIT240907",
    "start_date": "08-Sep-2024",
    "end_date": "20-Sep-2024",
    "days": 13,
    "qty": 6,
    "location": "Sri Aksata Ubud",
    "tl": "Nino Sumendap",
    "status": "Finish",
    "modems": "MC8, MC9, MC10, MC12, MC15, MC16",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali en Java"
  },
  {
    "tourcode": "AIS240916",
    "start_date": "17-Sep-2024",
    "end_date": "06-Oct-2024",
    "days": 20,
    "qty": 5,
    "location": "Swastika Bungalow",
    "tl": "Komang Merta",
    "status": "Finish",
    "modems": "MC17, MC18, MC19, MC20, MC21",
    "invoice_status": "Paid",
    "remark": "Rondreis Sunda Eilanden"
  },
  {
    "tourcode": "BAI240920R",
    "start_date": "21-Sep-2024",
    "end_date": "10-Oct-2024",
    "days": 20,
    "qty": 4,
    "location": "Le Polonia Hotel Medan",
    "tl": "Chairul Effendi",
    "status": "Finish",
    "modems": "MC22, MC23, MC24, MC25",
    "invoice_status": "Paid",
    "remark": "Rondreis Sumatra, Java en Bali"
  },
  {
    "tourcode": "SOD240928ACS",
    "start_date": "29-Sep-2024",
    "end_date": "10-Oct-2024",
    "days": 13,
    "qty": 4,
    "location": "Sriphala Resort & Spa Sanur",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "MC2, MC3, MC4, MC5",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali"
  },
  {
    "tourcode": "SOO240928T",
    "start_date": "29-Sep-2024",
    "end_date": "10-Oct-2024",
    "days": 13,
    "qty": 3,
    "location": "Sriphala Resort & Spa Sanur",
    "tl": "Pendot",
    "status": "Finish",
    "modems": "MC38, MC39, MC40",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali en Lombok"
  },
  {
    "tourcode": "SOJ241003T",
    "start_date": "04-Oct-2024",
    "end_date": "23-Oct-2024",
    "days": 20,
    "qty": 5,
    "location": "Erian Hotel Jakarta",
    "tl": "Empong Kuswoyo",
    "status": "Finish",
    "modems": "MC6, MC8, MC9, MC10, MC11",
    "invoice_status": "Paid",
    "remark": "Indonesie: Java, Bali en Gili eilanden"
  },
  {
    "tourcode": "AIL241003",
    "start_date": "04-Oct-2024",
    "end_date": "23-Oct-2024",
    "days": 20,
    "qty": 6,
    "location": "Jambuluwuk Thamrin Hotel Jakarta",
    "tl": "Bram Idrus",
    "status": "Finish",
    "modems": "MC12, MC13, MC14, MC15, MC16, MC17",
    "invoice_status": "Paid",
    "remark": "Ms. Blommaart, Ms. van der Put, Pty Valkenburg, Ms. de Jong, Pty DE COCK, Pty Vernes"
  },
  {
    "tourcode": "AIS241007R",
    "start_date": "08-Oct-2024",
    "end_date": "27-Oct-2024",
    "days": 20,
    "qty": 1,
    "location": "Sri Phala Sanur",
    "tl": "Komang Merta",
    "status": "Finish",
    "modems": "MC18",
    "invoice_status": "Paid",
    "remark": "Rondreis Sunda Eilanden"
  },
  {
    "tourcode": "BAI241011",
    "start_date": "12-Oct-2024",
    "end_date": "31-Oct-2024",
    "days": 20,
    "qty": 5,
    "location": "Le Polonia Hotel Medan",
    "tl": "Chairul Effendi",
    "status": "Finish",
    "modems": "MC17, MC19, MC21, MC41, MC42",
    "invoice_status": "Paid",
    "remark": "Rondreis Sumatra, Java en Bali"
  },
  {
    "tourcode": "SOD241012V",
    "start_date": "13-Oct-2024",
    "end_date": "25-Oct-2024",
    "days": 13,
    "qty": 2,
    "location": "Sri Phala Sanur",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "MC2, MC4",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali"
  },
  {
    "tourcode": "SOO241012V",
    "start_date": "13-Oct-2024",
    "end_date": "25-Oct-2024",
    "days": 13,
    "qty": 2,
    "location": "Abian Harmony Hotel Sanur",
    "tl": "Pendot",
    "status": "Finish",
    "modems": "MC38, MC39",
    "invoice_status": "Paid",
    "remark": "Indonesie: Bali en Lombok"
  },
  {
    "tourcode": "AIN241018R",
    "start_date": "19-Oct-2024",
    "end_date": "07-Nov-2024",
    "days": 20,
    "qty": 3,
    "location": "Le Polonia Hotel Medan",
    "tl": "Nurdin Nasution",
    "status": "Finish",
    "modems": "MC3, MC5, MC40",
    "invoice_status": "Paid",
    "remark": "Kirim ke Pak Arfan"
  },
  {
    "tourcode": "BAS241021R",
    "start_date": "22-Oct-2024",
    "end_date": "10-Nov-2024",
    "days": 20,
    "qty": 2,
    "location": "HT Office Sanur",
    "tl": "Piter",
    "status": "Finish",
    "modems": "MC36, MC37",
    "invoice_status": "Paid",
    "remark": "Bali Lombok"
  },
  {
    "tourcode": "SOJ241031S",
    "start_date": "01-Nov-2024",
    "end_date": "20-Nov-2024",
    "days": 20,
    "qty": 4,
    "location": "Erian Hotel Jakarta",
    "tl": "Empong Kuswoyo",
    "status": "Finish",
    "modems": "MC6, MC8, MC9, MC10",
    "invoice_status": "Paid",
    "remark": "WIFIindonesie (Mr. Vermeulen, Mr. Eikendal, Ms. Schrans)"
  },
  {
    "tourcode": "SOD241103T",
    "start_date": "04-Nov-2024",
    "end_date": "16-Nov-2024",
    "days": 13,
    "qty": 3,
    "location": "Sri Phala Sanur",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "MC35, MC38, MC39",
    "invoice_status": "Paid",
    "remark": "Bali Tour"
  },
  {
    "tourcode": "SOO241103S",
    "start_date": "04-Nov-2024",
    "end_date": "16-Nov-2024",
    "days": 13,
    "qty": 2,
    "location": "Swastika Bungalow",
    "tl": "Pendot",
    "status": "Finish",
    "modems": "MC41, MC42",
    "invoice_status": "Paid",
    "remark": "Bali & Lombok"
  },
  {
    "tourcode": "AIN241108",
    "start_date": "09-Nov-2024",
    "end_date": "28-Nov-2024",
    "days": 20,
    "qty": 2,
    "location": "Le Polonia Hotel Medan",
    "tl": "Chairul Effendi",
    "status": "Finish",
    "modems": "MC17, MC19, MC21",
    "invoice_status": "Paid",
    "remark": "Sumatra & Bali"
  },
  {
    "tourcode": "SOD241123T",
    "start_date": "24-Nov-2024",
    "end_date": "06-Dec-2024",
    "days": 13,
    "qty": 3,
    "location": "Sri Phala Sanur",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "MC20, MC25, MC27",
    "invoice_status": "Paid",
    "remark": "Sri Phala Sanur"
  },
  {
    "tourcode": "FIO241221C",
    "start_date": "22-Dec-2024",
    "end_date": "03-Jan-2025",
    "days": 13,
    "qty": 3,
    "location": "Sens Hotel Ubud",
    "tl": "Nino Sumendap",
    "status": "Finish",
    "modems": "MC19, MC20, MC25",
    "invoice_status": "Paid",
    "remark": "Ubud & Lombok"
  },
  {
    "tourcode": "BAT241221R",
    "start_date": "22-Dec-2024",
    "end_date": "03-Jan-2025",
    "days": 13,
    "qty": 2,
    "location": "Sri Phala Sanur",
    "tl": "Sofyan Manik",
    "status": "Finish",
    "modems": "MC9, MC10",
    "invoice_status": "Paid",
    "remark": "Sri Phala Sanur"
  },
  {
    "tourcode": "SOD241222S",
    "start_date": "23-Dec-2024",
    "end_date": "04-Jan-2025",
    "days": 13,
    "qty": 1,
    "location": "Sri Phala Sanur",
    "tl": "Pendot",
    "status": "Finish",
    "modems": "MC27",
    "invoice_status": "Paid",
    "remark": "Sanur Bali"
  },
  {
    "tourcode": "SOO250208S",
    "start_date": "09-Feb-2025",
    "end_date": "21-Feb-2025",
    "days": 13,
    "qty": 5,
    "location": "Swastika Bungalow",
    "tl": "Ell Pratama",
    "status": "Finish",
    "modems": "MC9, MC10, MC19, MC20, MC26",
    "invoice_status": "Paid",
    "remark": "Bali & Lombok"
  },
  {
    "tourcode": "BAT250208R",
    "start_date": "09-Feb-2025",
    "end_date": "21-Feb-2025",
    "days": 13,
    "qty": 1,
    "location": "Sri Aksata Ubud",
    "tl": "Komang Karung",
    "status": "Finish",
    "modems": "MC25",
    "invoice_status": "Paid",
    "remark": "Sri Aksata Ubud"
  },
  {
    "tourcode": "SOJ250227S",
    "start_date": "28-Feb-2025",
    "end_date": "19-Mar-2025",
    "days": 20,
    "qty": 1,
    "location": "Erian Hotel Jakarta",
    "tl": "Empong Kuswoyo",
    "status": "Finish",
    "modems": "MC29",
    "invoice_status": "Paid",
    "remark": "Kirim MC29"
  },
  {
    "tourcode": "SOO250329T",
    "start_date": "30-Mar-2025",
    "end_date": "11-Apr-2025",
    "days": 13,
    "qty": 2,
    "location": "Swastika Bungalow",
    "tl": "Nasri",
    "status": "Finish",
    "modems": "MC1, MC2",
    "invoice_status": "Paid",
    "remark": "Titip Venny, mau Mudik"
  },
  {
    "tourcode": "KIO250405B",
    "start_date": "06-Apr-2025",
    "end_date": "18-Apr-2025",
    "days": 13,
    "qty": 4,
    "location": "Sens Hotel Ubud",
    "tl": "Pendot",
    "status": "Finish",
    "modems": "MC3, MC4, MC5, MC6",
    "invoice_status": "Paid",
    "remark": "Sens Hotel Ubud"
  },
  {
    "tourcode": "FIO250419",
    "start_date": "20-Apr-2025",
    "end_date": "02-May-2025",
    "days": 13,
    "qty": 4,
    "location": "B.Saya Villa Ubud",
    "tl": "Komang Merta",
    "status": "Finish",
    "modems": "MC9, MC10, MC24, MC27",
    "invoice_status": "Paid",
    "remark": "B.Saya Villa Ubud"
  },
  {
    "tourcode": "SOO250425S",
    "start_date": "26-Apr-2025",
    "end_date": "09-May-2025",
    "days": 14,
    "qty": 1,
    "location": "Swastika Bungalow",
    "tl": "Pak Usman",
    "status": "Finish",
    "modems": "MC14",
    "invoice_status": "Paid",
    "remark": "Swastika Bungalow"
  },
  {
    "tourcode": "18048",
    "start_date": "30-Apr-2025",
    "end_date": "07-May-2025",
    "days": 8,
    "qty": 1,
    "location": "Theo - Lombok",
    "tl": "FIT",
    "status": "Finish",
    "modems": "MC4",
    "invoice_status": "Paid",
    "remark": "Miss Danielle Sullivan Zabala"
  },
  {
    "tourcode": "SOJ250501S",
    "start_date": "02-May-2025",
    "end_date": "21-May-2025",
    "days": 20,
    "qty": 2,
    "location": "Erian Hotel Jakarta",
    "tl": "Empong Kuswoyo",
    "status": "Finish",
    "modems": "MC1, MC6",
    "invoice_status": "Paid",
    "remark": "Erian Hotel Jakarta"
  },
  {
    "tourcode": "BAJ250501",
    "start_date": "02-May-2025",
    "end_date": "21-May-2025",
    "days": 20,
    "qty": 6,
    "location": "Jambuluwuk Thamrin Jakarta",
    "tl": "Bram Idrus",
    "status": "Finish",
    "modems": "MC3, MC13, MC20, MC21, MC34, MC37",
    "invoice_status": "Paid",
    "remark": "Wifi Kebawa semua"
  },
  {
    "tourcode": "AIN250509R",
    "start_date": "10-May-2025",
    "end_date": "29-May-2025",
    "days": 20,
    "qty": 1,
    "location": "Narasindo Medan",
    "tl": "Chairul Effendi",
    "status": "Finish",
    "modems": "MC36",
    "invoice_status": "Paid",
    "remark": "Rondreis Sumatra, Java en Bali"
  },
  {
    "tourcode": "BAT250510R",
    "start_date": "11-May-2025",
    "end_date": "23-May-2025",
    "days": 13,
    "qty": 3,
    "location": "Office HT Sanur",
    "tl": "Nino Sumendap",
    "status": "Finish",
    "modems": "MC9, MC10, MC24",
    "invoice_status": "Paid",
    "remark": "Pty Gnut, pty Russcher, Pty Stuivenberg"
  },
  {
    "tourcode": "AIS250512",
    "start_date": "13-May-2025",
    "end_date": "01-Jun-2025",
    "days": 20,
    "qty": 2,
    "location": "Office HT Sanur",
    "tl": "Komang Karung",
    "status": "Finish",
    "modems": "MC19, MC27",
    "invoice_status": "Paid",
    "remark": "Pty Schaap & pty Swarts"
  },
  {
    "tourcode": "SOJ250522V",
    "start_date": "23-May-2025",
    "end_date": "11-Jun-2025",
    "days": 20,
    "qty": 1,
    "location": "Erian Hotel Jakarta",
    "tl": "Empong Kuswoyo",
    "status": "Finish",
    "modems": "MC1",
    "invoice_status": "Paid",
    "remark": "Mr. Marvin Christopher Graper"
  },
  {
    "tourcode": "BAI250606",
    "start_date": "07-Jun-2025",
    "end_date": "26-Jun-2025",
    "days": 20,
    "qty": 3,
    "location": "HTS Medan",
    "tl": "Chairul Effendi",
    "status": "Finish",
    "modems": "MC19, MC27, MC36",
    "invoice_status": "Paid",
    "remark": "Sumatra & Bali"
  },
  {
    "tourcode": "AIS250609R",
    "start_date": "10-Jun-2025",
    "end_date": "29-Jun-2025",
    "days": 20,
    "qty": 1,
    "location": "Swastika Bungalow",
    "tl": "Komang Karung",
    "status": "Finish",
    "modems": "MC7",
    "invoice_status": "Paid",
    "remark": "Sunda Eilanden"
  },
  {
    "tourcode": "AIL250612",
    "start_date": "13-Jun-2025",
    "end_date": "02-Jul-2025",
    "days": 20,
    "qty": 3,
    "location": "Swiss-Belinn Wahid Hasyim Jakarta",
    "tl": "Bram Idrus",
    "status": "Finish",
    "modems": "MC9, MC10, MC24",
    "invoice_status": "Paid",
    "remark": "Wahid Hasyim Jakarta"
  },
  {
    "tourcode": "SOD250621S",
    "start_date": "22-Jun-2025",
    "end_date": "04-Jul-2025",
    "days": 12,
    "qty": 1,
    "location": "Sri Phala Sanur",
    "tl": "Yoga",
    "status": "Finish",
    "modems": "MC11",
    "invoice_status": "Paid",
    "remark": "Sanur Bali"
  },
  {
    "tourcode": "KIB250705B",
    "start_date": "06-Jul-2025",
    "end_date": "18-Jul-2025",
    "days": 12,
    "qty": 4,
    "location": "SenS Hotel & Spa Ubud",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "MC2, MC4, MC6, MC8",
    "invoice_status": "Paid",
    "remark": "Pty De Praeter, Pty De Brackeleer, Pty Sperling, Van seters"
  },
  {
    "tourcode": "BAT250705R",
    "start_date": "06-Jul-2025",
    "end_date": "18-Jul-2025",
    "days": 12,
    "qty": 3,
    "location": "Bakung Hotel Ubud",
    "tl": "Gede Suadnyana",
    "status": "Finish",
    "modems": "MC9, MC10, MC11",
    "invoice_status": "Paid",
    "remark": "Pty De Jaegere, Pty Vangrieken, Pty Motte"
  },
  {
    "tourcode": "BAI250708R",
    "start_date": "09-Jul-2025",
    "end_date": "28-Jul-2025",
    "days": 19,
    "qty": 2,
    "location": "Le Polonia Hotel Medan",
    "tl": "Nazarius Ophan",
    "status": "Finish",
    "modems": "MC1, MC3",
    "invoice_status": "Paid",
    "remark": "Pty Henkens, Pty Ceulemans"
  },
  {
    "tourcode": "FIS250708B",
    "start_date": "09-Jul-2025",
    "end_date": "28-Jul-2025",
    "days": 19,
    "qty": 3,
    "location": "Le Polonia Hotel Medan",
    "tl": "Nurdin Nasution",
    "status": "Finish",
    "modems": "MC13, MC20, MC21",
    "invoice_status": "Paid",
    "remark": "Pty Smits, Pty Kevin, Pty Carin"
  },
  {
    "tourcode": "BAJ250710R",
    "start_date": "11-Jul-2025",
    "end_date": "30-Jul-2025",
    "days": 19,
    "qty": 2,
    "location": "Swiss-Belinn Wahid Hasyim Jakarta",
    "tl": "Empong Kuswoyo",
    "status": "Finish",
    "modems": "MC16, MC24",
    "invoice_status": "Paid",
    "remark": "Mr. Calloens, Ms. Ceuppens"
  },
  {
    "tourcode": "FID250710",
    "start_date": "11-Jul-2025",
    "end_date": "30-Jul-2025",
    "days": 19,
    "qty": 2,
    "location": "de Braga by ARTOTEL Bandung",
    "tl": "Sugiarto",
    "status": "Finish",
    "modems": "MC33, MC34",
    "invoice_status": "Paid",
    "remark": "pty Bos, Pty Verhelst"
  },
  {
    "tourcode": "FIB250712C",
    "start_date": "13-Jul-2025",
    "end_date": "25-Jul-2025",
    "days": 12,
    "qty": 4,
    "location": "Bhuwana Ubud",
    "tl": "Nino Sumendap",
    "status": "Finish",
    "modems": "MC35, MC37, MC40, MC41",
    "invoice_status": "Paid",
    "remark": "Pty Game, Pty Hendriks, Pty Maulany, Pty Steringa"
  },
  {
    "tourcode": "FIO250712P",
    "start_date": "13-Jul-2025",
    "end_date": "25-Jul-2025",
    "days": 12,
    "qty": 1,
    "location": "Sens Hotel Ubud",
    "tl": "Komang Karung",
    "status": "Finish",
    "modems": "MC42",
    "invoice_status": "Paid",
    "remark": "Van Vlastuin Pty"
  },
  {
    "tourcode": "KIS250715P",
    "start_date": "16-Jul-2025",
    "end_date": "04-Aug-2025",
    "days": 19,
    "qty": 1,
    "location": "Le Polonia Hotel Medan",
    "tl": "Bram Idrus",
    "status": "Finish",
    "modems": "MC36",
    "invoice_status": "Paid",
    "remark": "Pty Denecker"
  },
  {
    "tourcode": "FID250717B",
    "start_date": "18-Jul-2025",
    "end_date": "04-Aug-2025",
    "days": 17,
    "qty": 2,
    "location": "de Braga by ARTOTEL Bandung",
    "tl": "Halim Karnadi",
    "status": "Finish",
    "modems": "MC5, MC12",
    "invoice_status": "Paid",
    "remark": "Pty Hoogeveen, Pty Broersen"
  },
  {
    "tourcode": "BAT250718",
    "start_date": "19-Jul-2025",
    "end_date": "01-Aug-2025",
    "days": 13,
    "qty": 4,
    "location": "Puri Ayu Cottage Ubud",
    "tl": "Ketut Sentosa",
    "status": "Finish",
    "modems": "MC7, MC8, MC14, MC15",
    "invoice_status": "Paid",
    "remark": "Pty Steyaert, Pty Van Reempts, Pty Dubkova, Ms. Veltman"
  },
  {
    "tourcode": "FIO250718B",
    "start_date": "19-Jul-2025",
    "end_date": "01-Aug-2025",
    "days": 13,
    "qty": 3,
    "location": "Sri Aksata Ubud",
    "tl": "Gede Suadnyana",
    "status": "Finish",
    "modems": "MC9, MC10, MC11",
    "invoice_status": "Paid",
    "remark": "Ubud Bali"
  },
  {
    "tourcode": "AIN250722R",
    "start_date": "23-Jul-2025",
    "end_date": "11-Aug-2025",
    "days": 19,
    "qty": 4,
    "location": "Le Polonia Hotel Medan",
    "tl": "Linda Samosir",
    "status": "Finish",
    "modems": "MC14, MC18, MC23, MC26",
    "invoice_status": "Paid",
    "remark": "Pty Mont, Pty De Vries, Pty De Kam, Pty Noe"
  },
  {
    "tourcode": "AIL250724R",
    "start_date": "25-Jul-2025",
    "end_date": "13-Aug-2025",
    "days": 19,
    "qty": 1,
    "location": "Swiss Belinn Wahid Hasyim Jakarta",
    "tl": "Ell Pratama",
    "status": "Finish",
    "modems": "MC2",
    "invoice_status": "Paid",
    "remark": "Pty Lievrouw"
  },
  {
    "tourcode": "FIB250725P",
    "start_date": "26-Jul-2025",
    "end_date": "08-Aug-2025",
    "days": 13,
    "qty": 2,
    "location": "Putri Ayu Cottage Ubud",
    "tl": "Nino Sumendap",
    "status": "Finish",
    "modems": "MC40, MC41",
    "invoice_status": "Paid",
    "remark": "Pty Van Wijngen, Pty Jagers"
  },
  {
    "tourcode": "SOK250725S",
    "start_date": "26-Jul-2025",
    "end_date": "08-Aug-2025",
    "days": 13,
    "qty": 4,
    "location": "Sri Aksata Ubud",
    "tl": "Pendot",
    "status": "Finish",
    "modems": "MC28, MC29, MC30, MC31",
    "invoice_status": "Paid",
    "remark": "Mr. Walbeek, Ms. Braber, Ms. Heilen, Ms. Verduin"
  },
  {
    "tourcode": "AIS250728",
    "start_date": "29-Jul-2025",
    "end_date": "17-Aug-2025",
    "days": 19,
    "qty": 2,
    "location": "Ari Putri Hotel Sanur",
    "tl": "Komang Karung",
    "status": "Finish",
    "modems": "MC15, MC16",
    "invoice_status": "Paid",
    "remark": "Mr. Zegers, Mr. De Blouwe"
  },
  {
    "tourcode": "FIS250729P",
    "start_date": "30-Jul-2025",
    "end_date": "18-Aug-2025",
    "days": 19,
    "qty": 4,
    "location": "Le Polonia Hotel Medan",
    "tl": "Sofyan Manik",
    "status": "Finish",
    "modems": "MC6, MC8, MC17, MC18",
    "invoice_status": "Paid",
    "remark": "Pty Kras, Pty Van Der Gaag, Pty Van Leeuwen"
  },
  {
    "tourcode": "SOJ250731S",
    "start_date": "01-Aug-2025",
    "end_date": "20-Aug-2025",
    "days": 19,
    "qty": 5,
    "location": "Erian Hotel Jakarta",
    "tl": "Empong Kuswoyo",
    "status": "Finish",
    "modems": "MC3, MC4, MC13, MC16, MC20",
    "invoice_status": "Paid",
    "remark": "Pax De Brij, pax Masselink, pax Ruijgrok, pax Couprie"
  },
  {
    "tourcode": "FID250731P",
    "start_date": "01-Aug-2025",
    "end_date": "20-Aug-2025",
    "days": 19,
    "qty": 1,
    "location": "de Braga by ARTOTEL Bandung",
    "tl": "Sugiarto",
    "status": "Finish",
    "modems": "MC1",
    "invoice_status": "Paid",
    "remark": "Pty Meis"
  },
  {
    "tourcode": "BAI250805",
    "start_date": "06-Aug-2025",
    "end_date": "25-Aug-2025",
    "days": 19,
    "qty": 2,
    "location": "Le Polonia Hotel Medan",
    "tl": "Chairul Effendi",
    "status": "Finish",
    "modems": "MC19, MC27",
    "invoice_status": "Paid",
    "remark": "Pty De Jong, Pty Hormann"
  },
  {
    "tourcode": "KIS250805B",
    "start_date": "06-Aug-2025",
    "end_date": "25-Aug-2025",
    "days": 19,
    "qty": 2,
    "location": "Le Polonia Hotel Medan",
    "tl": "Nurdin Nasution",
    "status": "Finish",
    "modems": "MC22, MC25",
    "invoice_status": "Paid",
    "remark": "Sumatra & Bali"
  },
  {
    "tourcode": "AIL250807",
    "start_date": "08-Aug-2025",
    "end_date": "27-Aug-2025",
    "days": 19,
    "qty": 1,
    "location": "Swiss Belinn Wahid Hasyim Jakarta",
    "tl": "Bram Idrus",
    "status": "Finish",
    "modems": "MC36",
    "invoice_status": "Paid",
    "remark": "Koers"
  },
  {
    "tourcode": "SOO250816T",
    "start_date": "17-Aug-2025",
    "end_date": "29-Aug-2025",
    "days": 12,
    "qty": 2,
    "location": "Bumas Hotel Sanur",
    "tl": "Pendot",
    "status": "Finish",
    "modems": "MC29, MC30",
    "invoice_status": "Paid",
    "remark": "Ms. de Vlieger, Mr Kwaaitaal"
  },
  {
    "tourcode": "AIL250904R",
    "start_date": "05-Sep-2025",
    "end_date": "24-Sep-2025",
    "days": 19,
    "qty": 3,
    "location": "Erian Hotel Jakarta",
    "tl": "Bram Idrus",
    "status": "Finish",
    "modems": "MC17, MC18, MC19",
    "invoice_status": "Paid",
    "remark": "Pty Kops, Pty Pauwels, Pty Baijens"
  },
  {
    "tourcode": "SOJ250904V",
    "start_date": "05-Sep-2025",
    "end_date": "24-Sep-2025",
    "days": 19,
    "qty": 7,
    "location": "Erian Hotel Jakarta",
    "tl": "Ophan",
    "status": "Finish",
    "modems": "MC23, MC24, MC25, MC26, MC28, MC29, MC30",
    "invoice_status": "Paid",
    "remark": "Java, Bali en Gili eilanden"
  },
  {
    "tourcode": "SOK250906T",
    "start_date": "07-Sep-2025",
    "end_date": "19-Sep-2025",
    "days": 12,
    "qty": 2,
    "location": "Sri Aksata Ubud",
    "tl": "Pendot",
    "status": "Finish",
    "modems": "MC2, MC3",
    "invoice_status": "Paid",
    "remark": "Clary, Mark"
  },
  {
    "tourcode": "AIT250906R",
    "start_date": "07-Sep-2025",
    "end_date": "19-Sep-2025",
    "days": 12,
    "qty": 1,
    "location": "Sri Aksata Ubud",
    "tl": "Gede Suadnyana",
    "status": "Finish",
    "modems": "MC1",
    "invoice_status": "Paid",
    "remark": "Kim"
  },
  {
    "tourcode": "AIS250915R",
    "start_date": "16-Sep-2025",
    "end_date": "05-Oct-2025",
    "days": 19,
    "qty": 1,
    "location": "Swastika Bungalow",
    "tl": "Komang Karung",
    "status": "Finish",
    "modems": "MC33",
    "invoice_status": "Paid",
    "remark": "Mr. Marinus"
  },
  {
    "tourcode": "AIN250919R",
    "start_date": "20-Sep-2025",
    "end_date": "09-Oct-2025",
    "days": 19,
    "qty": 4,
    "location": "Le Polonia Hotel Medan",
    "tl": "Chairul Effendi",
    "status": "Finish",
    "modems": "MC34, MC35, MC36, MC37",
    "invoice_status": "Paid",
    "remark": "Ms. Gruter, Mr. Vahl, Mr. Breukink, Ms. Van Der Zeeuw"
  },
  {
    "tourcode": "SOO250927T",
    "start_date": "28-Sep-2025",
    "end_date": "10-Oct-2025",
    "days": 12,
    "qty": 2,
    "location": "Swastika Bungalow",
    "tl": "Usman",
    "status": "Finish",
    "modems": "MC29, MC30",
    "invoice_status": "Paid",
    "remark": "Ms. Blom & Mr. Rüsse"
  },
  {
    "tourcode": "SOJ251002T",
    "start_date": "03-Oct-2025",
    "end_date": "22-Oct-2025",
    "days": 19,
    "qty": 6,
    "location": "Erian Hotel Jakarta",
    "tl": "Empong Kuswoyo",
    "status": "Finish",
    "modems": "MC1, MC2, MC3, MC4, MC5, MC6",
    "invoice_status": "Paid",
    "remark": "Ms. Boorsma, Ms. Wiegers, Mr. Mulder, Ms. Bouts, Ms. Vergoossen, Ms. Beijaard"
  },
  {
    "tourcode": "BAJ251002",
    "start_date": "03-Oct-2025",
    "end_date": "22-Oct-2025",
    "days": 19,
    "qty": 4,
    "location": "Jambuluwuk Thamrin Jakarta",
    "tl": "Eddy B",
    "status": "Finish",
    "modems": "MC7, MC8, MC9, MC10",
    "invoice_status": "Paid",
    "remark": "Mr. Duijs, Mr. Hack, Ms. Herrewyn, Ms. Molegraaf"
  },
  {
    "tourcode": "AIS251006",
    "start_date": "07-Oct-2025",
    "end_date": "26-Oct-2025",
    "days": 19,
    "qty": 2,
    "location": "Swastika Bungalow",
    "tl": "Komang Karung",
    "status": "Finish",
    "modems": "MC11, MC12",
    "invoice_status": "Paid",
    "remark": "Ms. Van Beek, Mr. Bakx"
  },
  {
    "tourcode": "BAT251011R",
    "start_date": "12-Oct-2025",
    "end_date": "24-Oct-2025",
    "days": 12,
    "qty": 3,
    "location": "Sri Aksata Ubud",
    "tl": "Gede Suadnyana",
    "status": "Finish",
    "modems": "MC13, MC14, MC15",
    "invoice_status": "Paid",
    "remark": "Ms. Weijer, Mr. Nuijs & Ms. Marlies"
  },
  {
    "tourcode": "SOK251011S",
    "start_date": "12-Oct-2025",
    "end_date": "24-Oct-2025",
    "days": 12,
    "qty": 1,
    "location": "Sri Aksata Ubud",
    "tl": "Jielly",
    "status": "Finish",
    "modems": "MC16",
    "invoice_status": "Paid",
    "remark": "Ms. Van Til"
  },
  {
    "tourcode": "SOD251011V",
    "start_date": "12-Oct-2025",
    "end_date": "24-Oct-2025",
    "days": 12,
    "qty": 3,
    "location": "Sri Phala Sanur",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "MC17, MC18, MC19",
    "invoice_status": "Paid",
    "remark": "Mr. Wiegerinck, Ms. De Haan, Mr. Ooms"
  },
  {
    "tourcode": "AIN251017R",
    "start_date": "18-Oct-2025",
    "end_date": "06-Nov-2025",
    "days": 19,
    "qty": 2,
    "location": "Le Polonia Hotel Medan",
    "tl": "Nurdin Nasution",
    "status": "Finish",
    "modems": "MC20, MC21",
    "invoice_status": "Paid",
    "remark": "Sumatra & Bali Tour"
  },
  {
    "tourcode": "SOJ251030S",
    "start_date": "31-Oct-2025",
    "end_date": "19-Nov-2025",
    "days": 19,
    "qty": 2,
    "location": "Erian Hotel Jakarta",
    "tl": "Empong Kuswoyo",
    "status": "Finish",
    "modems": "MC22, MC23",
    "invoice_status": "Paid",
    "remark": "Mr John de Wit, van Bergen"
  },
  {
    "tourcode": "SOO251101S",
    "start_date": "02-Nov-2025",
    "end_date": "14-Nov-2025",
    "days": 12,
    "qty": 4,
    "location": "Swastika Bungalow",
    "tl": "Pendot",
    "status": "Finish",
    "modems": "MC24, MC25, MC26, MC27",
    "invoice_status": "Paid",
    "remark": "Ms. Spanjer, Ms. van Santen, Mr.ten Broek, Mr. van den Oord"
  },
  {
    "tourcode": "SOD251101T",
    "start_date": "02-Nov-2025",
    "end_date": "14-Nov-2025",
    "days": 12,
    "qty": 7,
    "location": "Sri Phala Sanur",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "MC28, MC29, MC30, MC31, MC32, MC33, MC34",
    "invoice_status": "Paid",
    "remark": "Stella, Carla, Sandra, Nicole, koen, Leo, Huub"
  },
  {
    "tourcode": "SOD251206V",
    "start_date": "07-Dec-2025",
    "end_date": "19-Dec-2025",
    "days": 12,
    "qty": 1,
    "location": "Sri Phala Seminyak",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "MC33",
    "invoice_status": "Paid",
    "remark": "Ms. Mandy Luby"
  },
  {
    "tourcode": "KIO251220C",
    "start_date": "21-Dec-2025",
    "end_date": "02-Jan-2026",
    "days": 12,
    "qty": 2,
    "location": "Sens Hotel Ubud",
    "tl": "Gede Suadnyana",
    "status": "Finish",
    "modems": "MC34, MC35",
    "invoice_status": "Paid",
    "remark": "Mr. Jan Pieter de Graff"
  },
  {
    "tourcode": "KIB260404",
    "start_date": "05-Apr-2026",
    "end_date": "17-Apr-2026",
    "days": 12,
    "qty": 2,
    "location": "Sri Aksata Ubud",
    "tl": "Komang Sudira",
    "status": "Finish",
    "modems": "MC34, MC35",
    "invoice_status": "Paid",
    "remark": "Mr. Wim de Spae, Miss. Inge Huysmans"
  },
  {
    "tourcode": "FIO260418",
    "start_date": "18-Apr-2026",
    "end_date": "01-May-2026",
    "days": 13,
    "qty": 4,
    "location": "B.Saya Villa Ubud",
    "tl": "Nino Sumendap",
    "status": "Finish",
    "modems": "MC17, MC36, MC39, MC41",
    "invoice_status": "Paid",
    "remark": "Mr. Edwin Sleicher, Ms. Vanessa Wissink, Mr. Sebastiaan Deijkers, Mr. Eelko Vooijs"
  },
  {
    "tourcode": "SOO260425",
    "start_date": "26-Apr-2026",
    "end_date": "09-May-2026",
    "days": 13,
    "qty": 4,
    "location": "Swastika Bungalow",
    "tl": "Jielly",
    "status": "Finish",
    "modems": "MC1, MC2, MC3, MC4",
    "invoice_status": "Paid",
    "remark": "Miss Brigitta Christina, Miss Cynthia, Mr Jan Johannes, Mr Ruben Tacoma"
  },
  {
    "tourcode": "BAS260511",
    "start_date": "12-May-2026",
    "end_date": "31-May-2026",
    "days": 19,
    "qty": 2,
    "location": "Swastika Bungalow",
    "tl": "Komang Karung",
    "status": "Finish",
    "modems": "MC17, MC36",
    "invoice_status": "Paid",
    "remark": "Miss Jacqueline Mariëlle t Hardt, Miss Ingrid Alexandra Maria Metternich"
  },
  {
    "tourcode": "BAJ260521",
    "start_date": "22-May-2026",
    "end_date": "10-Jun-2026",
    "days": 19,
    "qty": 2,
    "location": "Santika Premiere Hayam Wuruk Jakarta",
    "tl": "Bram Idrus",
    "status": "Finish",
    "modems": "MC37, MC39",
    "invoice_status": "Paid",
    "remark": "Jakarta & Bali Tour"
  },
  {
    "tourcode": "SOJ260521",
    "start_date": "22-May-2026",
    "end_date": "10-Jun-2026",
    "days": 19,
    "qty": 1,
    "location": "Santika Premiere Hayam Wuruk Jakarta",
    "tl": "Pieter",
    "status": "Finish",
    "modems": "MC40",
    "invoice_status": "Paid",
    "remark": "Jakarta Tour"
  },
  {
    "tourcode": "SOD260708",
    "start_date": "09-Jul-2026",
    "end_date": "21-Jul-2026",
    "days": 12,
    "qty": 3,
    "location": "Sri Phala Sanur",
    "tl": "Komang Sudira",
    "status": "Running",
    "modems": "MC1, MC2, MC4",
    "invoice_status": "Paid",
    "remark": "Miss Julia Aimée De la Haije, Miss Kimberley van der Graaf, Miss Irma Van Vegchel",
    "device_pax": {
      "MC1": "Miss Julia Aimée De la Haije",
      "MC2": "Miss Kimberley van der Graaf",
      "MC4": "Miss Irma Van Vegchel"
    }
  },
  {
    "tourcode": "KIB260708",
    "start_date": "09-Jul-2026",
    "end_date": "21-Jul-2026",
    "days": 12,
    "qty": 2,
    "location": "Ubud, Pertiwi Bisma",
    "tl": "Nino Sumendap",
    "status": "Finish",
    "modems": "MC5, MC6",
    "invoice_status": "Paid",
    "remark": "Mr Gijs Barend Rudolphus Vloon, Miss Marjolein Denise T Van Acker"
  },
  {
    "tourcode": "KIS260710",
    "start_date": "13-Jul-2026",
    "end_date": "30-Jul-2026",
    "days": 18,
    "qty": 2,
    "location": "Medan, Polonia Hotel",
    "tl": "Nurdin Nasution",
    "status": "Running",
    "modems": "MC41, eSIM",
    "invoice_status": "Paid",
    "remark": "Mr Kristof Van den Broeck, Mr Jos Antoine Verbakel",
    "device_pax": {
      "MC41": "Mr Kristof Van den Broeck",
      "eSIM": "Mr Jos Antoine Verbakel"
    }
  },
  {
    "tourcode": "FIO260715",
    "start_date": "16-Jul-2026",
    "end_date": "28-Jul-2026",
    "days": 13,
    "qty": 1,
    "location": "Ubud, B.Saya Villa",
    "tl": "I Ketut Sentosa",
    "status": "Running",
    "modems": "MC39",
    "invoice_status": "Paid",
    "remark": "Mr Farley Robin Letsch",
    "device_pax": {
      "MC39": "Mr Farley Robin Letsch"
    }
  },
  {
    "tourcode": "AIL260716",
    "start_date": "17-Jul-2026",
    "end_date": "05-Aug-2026",
    "days": 20,
    "qty": 1,
    "location": "Jakarta, Santika Hayam Wuruk",
    "tl": "Bram Idrus",
    "status": "Running",
    "modems": "MC3",
    "invoice_status": "Paid",
    "remark": "Miss Esmee Dohmen",
    "device_pax": {
      "MC3": "Miss Esmee Dohmen"
    }
  },
  {
    "tourcode": "FIS260717",
    "start_date": "18-Jul-2026",
    "end_date": "06-Aug-2026",
    "days": 20,
    "qty": 1,
    "location": "HT Sumatra Office",
    "tl": "Linda Samosir",
    "status": "Running",
    "modems": "MC36",
    "invoice_status": "Paid",
    "remark": "Mr Gerrit Johannes Kuijvenhoven",
    "device_pax": {
      "MC36": "Mr Gerrit Johannes Kuijvenhoven"
    }
  },
  {
    "tourcode": "KIB260722",
    "start_date": "23-Jul-2026",
    "end_date": "04-Aug-2026",
    "days": 13,
    "qty": 3,
    "location": "Ubud, Sri Aksata",
    "tl": "Gede Suadnyana",
    "status": "Running",
    "modems": "MC7, MC8, MC12",
    "invoice_status": "Paid",
    "remark": "Miss Kimberley Winifreda D van Megroot, Mr Aalbertus Jørgen Wagensveld",
    "device_pax": {
      "MC7": "Miss Kimberley Winifreda",
      "MC8": "Mr Aalbertus Jørgen Wagensveld",
      "MC12": "Family Guest"
    }
  },
  {
    "tourcode": "SOD260722",
    "start_date": "23-Jul-2026",
    "end_date": "04-Aug-2026",
    "days": 13,
    "qty": 2,
    "location": "Sanur, Abian Harmony",
    "tl": "Komang Sudira",
    "status": "Running",
    "modems": "MC10, MC11",
    "invoice_status": "Paid",
    "remark": "Sanur Abian Harmony"
  },
  {
    "tourcode": "BAJ260723",
    "start_date": "24-Jul-2026",
    "end_date": "12-Aug-2026",
    "days": 20,
    "qty": 1,
    "location": "Jakarta, Jambuluwuk Thamrin",
    "tl": "Sugiarto",
    "status": "Running",
    "modems": "MC33",
    "invoice_status": "Paid",
    "remark": "Miss Kristel Van Strydonck",
    "device_pax": {
      "MC33": "Miss Kristel Van Strydonck"
    }
  },
  {
    "tourcode": "BAI260723",
    "start_date": "24-Jul-2026",
    "end_date": "12-Aug-2026",
    "days": 20,
    "qty": 1,
    "location": "HT Sumatra Office",
    "tl": "Halim Karnadi",
    "status": "Running",
    "modems": "MC13",
    "invoice_status": "Paid",
    "remark": "Miss Monica Caroline W. Sykora",
    "device_pax": {
      "MC13": "Miss Monica Caroline W. Sykora"
    }
  },
  {
    "tourcode": "SOJ260723",
    "start_date": "24-Jul-2026",
    "end_date": "12-Aug-2026",
    "days": 20,
    "qty": 4,
    "location": "Santika Premiere Hayam Wuruk, Jakarta",
    "tl": "Ophan",
    "status": "Running",
    "modems": "MC30, MC35, MC37, MC40",
    "invoice_status": "Paid",
    "remark": "Miss Margaretha, Mr Maximiliaan, Miss Janneke, Mr Ludovicus",
    "device_pax": {
      "MC30": "Miss Margaretha",
      "MC35": "Mr Maximiliaan",
      "MC37": "Miss Janneke",
      "MC40": "Mr Ludovicus"
    }
  },
  {
    "tourcode": "FID260730",
    "start_date": "31-Jul-2026",
    "end_date": "19-Aug-2026",
    "days": 20,
    "qty": 2,
    "location": "Bandung, de Braga",
    "tl": "Sofyan Manik",
    "status": "Upcoming",
    "modems": "MC19, MC21",
    "invoice_status": "Pending",
    "remark": "Mr Nicky Stephanus Brouwer, Miss Anne Maria Zandstra",
    "device_pax": {
      "MC19": "Mr Nicky Stephanus Brouwer",
      "MC21": "Miss Anne Maria Zandstra"
    }
  },
  {
    "tourcode": "BAS260727",
    "start_date": "28-Jul-2026",
    "end_date": "16-Aug-2026",
    "days": 20,
    "qty": 3,
    "location": "Sanur, Abian Harmony",
    "tl": "Komang Karung",
    "status": "Upcoming",
    "modems": "MC14, MC15, MC16",
    "invoice_status": "Pending",
    "remark": "Mr Petrus Christianus, Mr Antonius Johannes, Miss Leontine Cornelia"
  },
  {
    "tourcode": "SOO260729",
    "start_date": "30-Jul-2026",
    "end_date": "11-Aug-2026",
    "days": 13,
    "qty": 7,
    "location": "Sanur, Abian Harmony",
    "tl": "Subhan Saputra",
    "status": "Upcoming",
    "modems": "MC20, MC22, MC23, MC24, MC25, MC26, MC27",
    "invoice_status": "Pending",
    "remark": "Miss Jolijn Tooten, Miss Nikki Hanna, Mr Martin Jozef, Mr Jesse Marijn, Miss Kirsten Janine, Mr Mario, Mr Jordi"
  },
  {
    "tourcode": "FIO260729",
    "start_date": "30-Jul-2026",
    "end_date": "11-Aug-2026",
    "days": 13,
    "qty": 2,
    "location": "Ubud B Saya Villa",
    "tl": "Nino Sumendap",
    "status": "Upcoming",
    "modems": "MC28, MC29",
    "invoice_status": "Pending",
    "remark": "Miss Elsbeth Femke de Vries, Mr Maico Marinus Petrus Gijsbertus Meyer"
  },
  {
    "tourcode": "SOJ260730",
    "start_date": "31-Jul-2026",
    "end_date": "19-Aug-2026",
    "days": 20,
    "qty": 1,
    "location": "Jakarta, Santika Premiere Hayam Wuruk",
    "tl": "Empong Kuswoyo",
    "status": "Upcoming",
    "modems": "MC32",
    "invoice_status": "Pending",
    "remark": "Miss Annelies Van Geert",
    "device_pax": {
      "MC32": "Miss Annelies Van Geert"
    }
  }
];

export async function GET() {
  try {
    const { data, error } = await supabase
      .from("tour_rental_logs")
      .select("*")
      .order("created_at", { ascending: false });

    if (!error && data) {
      const localData = readJsonStore<any[]>("tour_rentals.json", MASTER_TOUR_LOGS);
      const combined = [...data];
      for (const loc of localData) {
        if (!combined.some((t) => (loc.tourcode && t.tourcode === loc.tourcode) || (loc.id && t.id === loc.id))) {
          combined.unshift(loc);
        }
      }
      writeJsonStore("tour_rentals.json", combined);
      return jsonNoCache(combined);
    }
  } catch (err) {
    console.warn("Supabase tour_rental_logs query skipped/failed, using local store:", err);
  }

  const localData = readJsonStore<any[]>("tour_rentals.json", MASTER_TOUR_LOGS);
  return jsonNoCache(localData);
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const {
      tourcode,
      start_date,
      end_date,
      days,
      qty,
      location,
      tl,
      status,
      modems,
      invoice_status,
      remark,
      notes,
      device_pax,
    } = body;

    const payload: Record<string, any> = {
      tourcode: (tourcode || `TOUR-${Date.now()}`).trim(),
      start_date: start_date || new Date().toISOString().split("T")[0],
      end_date: end_date || "",
      days: Number(days || 1),
      qty: Number(qty || 1),
      location: location || null,
      tl: tl || null,
      status: status || "Upcoming",
      modems: modems || "",
      invoice_status: invoice_status || "Unpaid",
      remark: remark || null,
      notes: notes || null,
      device_pax: device_pax || {},
      created_at: new Date().toISOString(),
    };

    if (body.id && body.id.length > 20 && body.id.includes("-")) {
      payload.id = body.id;
    } else if (typeof crypto !== "undefined" && crypto.randomUUID) {
      payload.id = crypto.randomUUID();
    } else {
      payload.id = `tour-${Date.now()}`;
    }

    // Dual write local store
    const list = readJsonStore<any[]>("tour_rentals.json", MASTER_TOUR_LOGS);
    const existingIdx = list.findIndex((t: any) => (t.tourcode && t.tourcode === payload.tourcode) || (t.id && t.id === payload.id));
    if (existingIdx >= 0) {
      list[existingIdx] = { ...list[existingIdx], ...payload };
    } else {
      list.unshift(payload);
    }
    writeJsonStore("tour_rentals.json", list);

    // Try saving to Supabase if table exists
    try {
      const sbPayload = { ...payload };
      if (sbPayload.id && !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(sbPayload.id)) {
        delete sbPayload.id;
      }
      const { error: insErr } = await supabase.from("tour_rental_logs").insert([sbPayload]);
      if (insErr) {
        console.warn("Supabase insert warning, falling back to update:", insErr.message);
        const { error: updErr } = await supabase
          .from("tour_rental_logs")
          .update(sbPayload)
          .eq("tourcode", payload.tourcode);
        if (updErr) console.warn("Supabase update error:", updErr.message);
      }
    } catch (e) {
      console.warn("Supabase tour_rental_logs insert skipped:", e);
    }

    return jsonNoCache(payload);
  } catch (err: any) {
    return jsonNoCache({ error: err?.message || "Insert failed" }, 500);
  }
}

export async function PUT(request: Request) {
  try {
    const body = await request.json();
    const {
      id,
      tourcode,
      start_date,
      end_date,
      days,
      qty,
      location,
      tl,
      status,
      modems,
      invoice_status,
      remark,
      notes,
      device_pax,
    } = body;

    if (!id && !tourcode) {
      return jsonNoCache({ error: "Rental ID or Tourcode is required" }, 400);
    }

    const updates: Record<string, any> = {};
    if (tourcode !== undefined) updates.tourcode = tourcode;
    if (start_date !== undefined) updates.start_date = start_date;
    if (end_date !== undefined) updates.end_date = end_date;
    if (days !== undefined) updates.days = Number(days);
    if (qty !== undefined) updates.qty = Number(qty);
    if (location !== undefined) updates.location = location;
    if (tl !== undefined) updates.tl = tl;
    if (status !== undefined) updates.status = status;
    if (modems !== undefined) updates.modems = modems;
    if (invoice_status !== undefined) updates.invoice_status = invoice_status;
    if (remark !== undefined) updates.remark = remark;
    if (notes !== undefined) updates.notes = notes;
    if (device_pax !== undefined) updates.device_pax = device_pax;

    // Dual update local store
    const list = readJsonStore<any[]>("tour_rentals.json", MASTER_TOUR_LOGS);
    let updatedItem: any = { id, tourcode, ...updates };
    const existingIdx = list.findIndex((t: any) => (id && t.id === id) || (tourcode && t.tourcode === tourcode));
    if (existingIdx >= 0) {
      list[existingIdx] = { ...list[existingIdx], ...updates };
      updatedItem = list[existingIdx];
    } else {
      list.unshift(updatedItem);
    }
    writeJsonStore("tour_rentals.json", list);

    // Try updating Supabase
    try {
      let q = supabase.from("tour_rental_logs").update(updates);
      if (id) await q.eq("id", id);
      else if (tourcode) await q.eq("tourcode", tourcode);
    } catch (e) {
      console.warn("Supabase tour_rental_logs update skipped:", e);
    }

    return jsonNoCache(updatedItem);
  } catch (err: any) {
    return jsonNoCache({ error: err?.message || "Update failed" }, 500);
  }
}

export async function DELETE(request: Request) {
  try {
    const { id, tourcode } = await request.json();

    if (!id && !tourcode) {
      return jsonNoCache({ error: "Rental ID or Tourcode is required" }, 400);
    }

    // Dual delete local store
    const list = readJsonStore<any[]>("tour_rentals.json", MASTER_TOUR_LOGS);
    const filtered = list.filter((t: any) => {
      if (id && t.id === id) return false;
      if (tourcode && t.tourcode === tourcode) return false;
      return true;
    });
    writeJsonStore("tour_rentals.json", filtered);

    // Try deleting from Supabase
    try {
      let query = supabase.from("tour_rental_logs").delete();
      if (id) await query.eq("id", id);
      else if (tourcode) await query.eq("tourcode", tourcode);
    } catch (e) {
      console.warn("Supabase tour_rental_logs delete skipped:", e);
    }

    return jsonNoCache({ success: true });
  } catch (err: any) {
    return jsonNoCache({ error: err?.message || "Delete failed" }, 500);
  }
}
